### ISSUE TITLE
error when writing file with no filetype

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-signify#101]
If I write/save a file that was restored from a session (which does not set up filetype autocmds, and `&ft` is empty), `:w`riting the file causes:

> Error detected while processing BufWritePost Auto commands for "*":
> E121: Undefined variable: b:sy_path
> E116: Invalid arguments for function sy#start

Editing the file with `:e` to load the syntax/filetype plugins fixes the issue, even after setting `:set ft=` again (I guess because autocmds are already set up).

I realize this is probably an edge case (I assume most people gave up on vim sessions), so I will try to debug it myself if it annoys me enough. Just putting it here to see if anyone else ran into it. I _think_ it started happening since the last 5 or so commits.

**Comment by PhilRunninger** [comment]
I just stumbled on this issue while debugging my own `vim-sessions` plugin. It was not setting the filetypes correctly after sourcing the session file. Your suggestion to use `nested` fixed it. Thanks!
