### ISSUE TITLE
Fold unchanged lines

### ISSUE THREAD

**Issue by fritzophrenic** [mhinz/vim-signify#118]
For a nice overview of what you've changed, it would be nice to have a command to fold away all unchanged lines (with context would be great).

I envision something like `:SyFold` would save off a "view", then set foldexpr to a function that would show only lines that have one of signify's indicators, plus one line before and after for context (especially for the deletions). Revealing one level of folding should show 3-6 more lines of context per change, and revealing one more level should show the whole file.

Then another command `:SyUnfold` would restore the view, so that the foldmethod and any manually open/closed folds would be restored from before the `:SyFold` command.

I might work on this at some point, but I'm pretty busy so I figured I'd post the idea here in case somebody else finds time before I do.

**Comment by mhinz** [comment]
@jamessan I'm done from my side: https://github.com/mhinz/vim-signify/commits/folding
