### ISSUE TITLE
disable background colors

### ISSUE THREAD

**Issue by Thanatermesis** [mhinz/vim-signify#128]
To change the background colors can make it look ugly, and some colorschemes doesn't supports this well, maybe there should be an option to enable/disable the changing of background colors and just use the foreground ones

**Comment by hoto** [comment]
I'm using xoria256 coor scheme and it has simmilar problem with SignColumn displaying in wrong color
quickest fix I found for this is to overwrite SignColumn background in `.vimrc`

    highlight SignColumn guibg=#131313
