### ISSUE TITLE
"Command terminated"

### ISSUE THREAD

**Issue by simendsjo** [mhinz/vim-signify#151]
After a recent update on master, I get the error as shown in the subject when opening a file. Starting vim with logging reveals the following:

```
line 2: sourcing "/home/simendsjo/.vim/vimfiles/bundle/vim-signify/autoload/sy/util.vim"
finished sourcing /home/simendsjo/.vim/vimfiles/bundle/vim-signify/autoload/sy/util.vim
continuing in function sy#start..sy#repo#detect..sy#repo#get_diff_git
chdir(/home/simendsjo/tmp/)
/home/simendsjo/tmp
Calling shell to execute: "(git diff --no-color --no-ext-diff -U0  -- 't.txt') >/tmp/vVvrlpY/1 2>&1"
chdir(/home/simendsjo/tmp)
/home/simendsjo/tmp
Calling shell to execute: "(svn diff --diff-cmd diff -x -U0  -- '/home/simendsjo/tmp/t.txt') >/tmp/vVvrlpY/2 2>&1"
Command terminated
```

I didn't have svn installed, and there is no svn repo in my path. The above log is taken after I installed svn, so it's not related to a missing binary. Not sure if it's related to svn or even signify though :/

**Comment by simendsjo** [comment]
No, no crashes. I used `vim -V9log.txt somefile.txt`

**Comment by jamessan** [comment]
What happens if you run `svn diff --diff-cmd diff -x -U0  -- '/home/simendsjo/tmp/t.txt'` manually from within `/home/simendsjo/tmp`?

**Comment by simendsjo** [comment]
Ah, not good..

```
$ svn diff --diff-cmd diff -x -U0 -- '/home/simendsjo/tmp/t.txt'
[1]    19929 segmentation fault (core dumped)  svn diff --diff-cmd diff -x -U0 -- '/home/simendsjo/tmp/t.txt'
```

**Comment by jamessan** [comment]
Closing this issue then.  I'd suggesting filing a bug with your distribution, if you're using their svn package.

**Comment by simendsjo** [comment]
Thanks. Adding a link back to the forum post in case someone else comes along with the same issue: https://bbs.archlinux.org/viewtopic.php?pid=1490801

**Comment by jamessan** [comment]
Looks like it might be [this bug](https://bugs.archlinux.org/task/38069).

**Comment by simendsjo** [comment]
Yes, thanks. I found it too while digging around gdb to get some more info.
I only had a single path in `LD_LIBRARY_PATH`, which didn't exist anymore after I uninstalled a package.
