### ISSUE TITLE
Setting to Update On Focus Gained Eats Clipboard

### ISSUE THREAD

**Issue by angelic-sedition** [mhinz/vim-signify#152]
If I put `let g:signify_update_on_focusgained = 1` in my ~/.vimrc, the + register becomes empty every time gvim gains focus. I also have `set clipboard=unnamedplus`.

**Comment by jamessan** [comment]
I can't reproduce it.  Can you remove other plugins to see if they're affecting this?

**Comment by angelic-sedition** [comment]
I don't know what was happening, but I don't think it was signify's fault. I updated all my plugins, and it stopped happening. I have too many plugins to have any idea what the cause was.

**Comment by angelic-sedition** [comment]
It started happening again. If I figure out the issue, I'll post it here.
