### ISSUE TITLE
Signify should handle "p4 monitor" failures better

### ISSUE THREAD

**Issue by dbarnett** [mhinz/vim-signify#153]
Signify's perforce support added a dependency on "p4 monitor" in 4d3674d431. Not all p4 configurations support the monitor command, causing signify to just fail silently. This is pretty bad default behavior.

The check should be made more precise so that it fails more visibly. It was originally just to prevent a hang, but if there's no perforce server available then it should show a warning message or at least some troubleshooting hint about the failure in the `:SignifyDebug` output. https://github.com/mhinz/vim-signify/issues/131#issuecomment-66685175 suggests even just replacing with "p4 info" would work just as well and wouldn't kill signify's perforce support for configurations without the monitor command.

The `g:signify_vcs_cmd` configuration in 67b1e89281 isn't a bad idea, but it's a really obscure answer for affected users to unbreak their perforce support. It's really really not obvious what all that junk is in the command for and how to modify it properly.

**Comment by jamessan** [comment]
Neither Marco nor I have experience with perforce or the ability to test suggested changes, so we're relying on the community here.  If replacing `p4 monitor` with `p4 info` is an acceptable fix, then I'll do that.

**Comment by dbarnett** [comment]
@mattsawyer77 @m-fonseca
All I can say for sure is that `p4 monitor` doesn't work for me. `p4 info` certainly would, but someone would need to verify that has the right properties to solve the original case that was hanging in #131. Since the `p4 monitor` change was added pretty unceremoniously and completely breaks some people, I'd suggest just switching it to `p4 info` and asking folks to report an issue if they see regressions.

**Comment by mattsawyer77** [comment]
I actually read about this recently in the perforce documentation. They suggest issuing a p4 info command when you're not sure if the server is reachable; this fails quickly without hanging.
