### ISSUE TITLE
Neovim -- seems like on autoread, does not update?

### ISSUE THREAD

**Issue by unphased** [mhinz/vim-signify#155]
Please let me know if you can't reproduce. 

The steps:

- Take a file, edit it so that signify makes many markers (I use git). 
- Then commit the file, and go back into the file and run `:checktime` to force auto refresh. This should remove all the signs! (Of course i have autocommands set up to run `checktime`, but I *believe* that's unrelated.) This works in vim but not in neovim, but neovim is properly re-reading the file (that can be checked by modifying the file outside, e.g. `echo "" >> file` then doing the `:checktime`).

**Comment by mhinz** [comment]
Actually I can't even reproduce it for Vim. :-)

Per default Sy only updates signs on `BufRead` and `BufWritePost` events. `:checktime` doesn't trigger either of these. Commiting a file (and adding it to the index the step before) only changes the atime (access time) of a file, but not the ctime (change time). Therefore `:checktime` sees no actual changes. According to `:h :checktime` this *reloads* the file, but that reloading doesn't seem to involve triggering `BufRead`, so `sy#start()` never gets called and the sign column isn't get updated.

If you actually change the file via `echo >> file` (or simply `touch file`), `:checktime` works as expected.

I'm looking into it.

**Comment by unphased** [comment]
Interesting. Seems like the old method (that I copied from vim wikia somewhere) to auto refresh no longer works in vanilla vim either. It used to work...

**Comment by mhinz** [comment]
So, is `:SignifyRefresh` good enough for your purpose?

**Comment by unphased** [comment]
well i bet it works real well, but the main thing is I would like to figure out how to get vim and neovim to properly update the file and detect when it changes on the filesystem. As far as I can tell any time that vim reloads a file buffer the signify signs will get updated

**Comment by unphased** [comment]
FWIW it still works great in OSX but seems to not work on Linux

**Comment by mhinz** [comment]
I'm really just guessing now.. could it be that certain mount flags are set that alter time stats? Check the `mount` output for `noatime`, `nodirtime` etc. If so, try re-mounting without them, for testing purposes.

**Comment by unphased** [comment]
Haha, ok. I'll need to learn what any of those things are now.

**Comment by mhinz** [comment]
Unfortunately I don't have a Linux VM available right now, but I'll set it up later on.

It should be enough if you look for `-o` in the manpage of `mount`. Most flags should be explained there.

**Comment by mhinz** [comment]
Is this still an issue?

**Comment by unphased** [comment]
It delightfully appears to have started working again. BTW i think the issue never had anything to do with Signify in the first place, and obviously once the buffer gets reloaded the gutter is properly updated.
