### ISSUE TITLE
`‾` won't render in XTerm using Monaco as font

### ISSUE THREAD

**Issue by mtglsk** [mhinz/vim-signify#156]
This is the `The first line was removed. It's a special case of the `_` sign.`.

I'm using Monaco as font and afaik XTerm doesn't substitute fonts, so if the font doesn't have the glyph, it won't render. Maybe an em-dash would be a better choice?

DejaVu Sans Mono:
![1](https://cloud.githubusercontent.com/assets/10101321/7127476/39dcd8c6-e245-11e4-9720-df4afd7a5ae9.png)

Monaco:
![2](https://cloud.githubusercontent.com/assets/10101321/7127477/3e959344-e245-11e4-83b1-431427941f72.png)

**Comment by jamessan** [comment]
Then either use a better font, get Monaco's author to add that glyph, or change what character is used by letting `g:signify_sign_delete_first_line` in your vimrc (as documented in `:help g:signify_sign_delete_first_line`).

**Comment by mtglsk** [comment]
This is a pretty rare glyph, Monaco, Ubuntu Mono, Consolas, Droid Sans Mono don't have it (all with fairly good UTF-8 coverage). Rendering it will be slow with most fonts, because the terminal would need to use substitution.

**Comment by jamessan** [comment]
Works fine for me in xterm using `-fn -misc-fixed-medium-r-normal--18-120-100-100-c-90-iso10646-1` or `-fa 'DejaVu Sans Mono -fs 10` (the two I typically use).  DejaVu is also essentially the standard monospace font on most distributions I've used.
