### ISSUE TITLE
Prompts for password when viewing someone else's files under CVS

### ISSUE THREAD

**Issue by rkennedy** [mhinz/vim-signify#158]
If I visit another user's CVS sandbox and open a file, Vim doesn't immediately display the file. Instead, it prints `Password:` at the bottom of the screen. (Pressing <kbd>Enter</kbd> three times eventually dismisses the prompt and displays the file, but probably without any diff marks.)

The problem is that `cvs` uses the *CVS/Root* file to determine where the repository files are kept, and that includes the user name of who checked it out. For example:

```text
:ext:otheruser@cvsserver.example.com:/sourcecode/CVS
```

Since I'm not logged in as otheruser, `cvs` needs a password before it can connect using that string.

The fix is to use the `cvs -d` option to override the repository's *CVS/Root* file, but I don't see a way of configuring Sy for that. The `g:signify_diffoptions` setting is close, but it needs to control something *before* `diff` on the command line, not after.

**Comment by mhinz** [comment]
Hi.

I intend to make the _entire_ command available for configuration. It will look something like this:

```vim
let g:signify_vcs_git = 'git diff --no-color --no-ext-diff -U0 -- %'
```

Whereas the `%` will be replaced with the full path to the current buffer. This should make all these configuration problems go away. (As long as it doesn't change the output format, of course.)

**Comment by mhinz** [comment]
Please try this:

`git pull && git checkout cmd-options`

Then put this in your vimrc:

`let g:signify_vcs_cmds = { 'cvs': 'cvs diff -U0 -- %f',' }`

Here `%f` will be replaced by the actual file path.

**Comment by rkennedy** [comment]
That works for me. Thanks for your help.

For reference, here's what I used:

```vim
let g:signify_vcs_cmds = { 'cvs': 'cvs -d '. $CVSROOT .' diff -U0 -- %f' }
```

**Comment by mhinz** [comment]
Splendid! There are still some things to fix in this branch, but I'll try to polish it today and merge into master tomorrow.

**Comment by mhinz** [comment]
It got merged into master yesterday.

@rkennedy I'm not a CVS user. Do you think `cvs -d '. $CVSROOT .' diff -U0 -- %f` would be a good default for all CVS users?

**Comment by rkennedy** [comment]
It's *often* set, but not *always*. In addition, I have a feeling that my situation (browsing other people's sandboxes) isn't very common, so most people wouldn't need to include `$CVSROOT` in their commands anyway.

Rather than adding the `-d` option in the default settings, I think it would be better to leave it out, but demonstrate it in the documentation of the `signify_vcs_cmds` setting.

**Comment by mhinz** [comment]
> Rather than adding the -d option in the default settings, I think it would be better to leave it out, but demonstrate it in the documentation of the signify_vcs_cmds setting.

I guess this is already done.

Well then, I think this can be closed now. Thanks for reporting the issue!
