### ISSUE TITLE
not working with perforce

### ISSUE THREAD

**Issue by mattsawyer77** [mhinz/vim-signify#161]
Not sure when this was introduced, because I haven't used vim in a while. But I now see that signify doesn't seem to be working for my anymore with Perforce workspaces. The SignifyDebug command shows me this:

```
<file name here>
===============================================================================================================
    active  =  1
    buffer  =  4
      type  =  unknown
     stats  =  -1 added, -1 changed, -1 removed
    id_top  =  256
     hunks  =  []
```

What info do you need from me to troubleshoot this issue?

**Comment by jamessan** [comment]
The output of `:10verbose call sy#repo#get_diff_perforce()` and what happens when you run the p4 commands manually in the same directory Vim is running them should help.

**Comment by jamessan** [comment]
@mhinz Might be a good idea to have `:SyDebug` display the commands it ran to try and detect differences as well as their output.

**Comment by mattsawyer77** [comment]
```
Calling shell to execute: "('p4 info 2>&1 >'/dev/null && env P4DIFF=diff p4 diff -dU0  '<file name here>') >/var/folders/nw/y21165jd1494pbznn432x5nw0000gn/T/vY3dlJJ/8 2>&1"
```
Running this from a terminal produces the following:
```
zsh: no such file or directory: p4 info 2>&1 >/dev/null
```
maybe there's a compatibility issue between zsh and signify?

If I omit the quotes around ```p4 info 2>&1 >``` the command seems to work as expected.

**Comment by jamessan** [comment]
I've reverted (in c2fc1dc7) the change that was introduced in #157 since that wasn't correct and is causing your current problem.

#157 was supposed to fix an issue with Sy's perforce integration when using Gvim.  I'd be interested to see if you can reproduce that problem with the supposed fix reverted so we can try and come up with the proper fix.

**Comment by jamessan** [comment]
Actually, I think I see what the original problem was and that should be fixed now.

**Comment by mhinz** [comment]
I just merged the `cmd-options` branch that replaces `g:signify_diffoptions` by `g:signify_vcs_commands` which allows to specfiy the entire command:

```vim
let g:signigy_vcs_cmd = { 'perforce': p4 info >%n 2>&1 && env P4DIFF=diff p4 diff -dU0 %f' }
```

The command above is the default now.

**Comment by mhinz** [comment]
Now `:SignifyDebugDiff` runs a diff for the current file and just prints it (it doesn't alter the current signs).

**Comment by mhinz** [comment]
Could you test if this works without problems:

```vim
g:signify_vcs_cmds = { 'perforce': 'p4 info >%n 2>&1 && env P4DIFF=%d p4 diff -dU0 %f' }
```

**Comment by mattsawyer77** [comment]
I just updated the plugin, and it works now. Thanks for the quick turnaround.
