### ISSUE TITLE
Nasty breakage if the directory the file was in no longer exists

### ISSUE THREAD

**Issue by kballard** [mhinz/vim-signify#162]
With the recent changes to this plugin, after saving a file at a given path, if the folder the file was saved in is removed, vim-signify breaks quite badly. This is true even if the buffer had its associated path changed with `:file`.

By "breaks quite badly" I mean any time an autocommand is triggered that calls `sy#start` it ends up throwing errors. For example:

> ```
Error detected while processing function sy#start..sy#repo#detect..sy#repo#get_diff_git..<SNR>215_run:
line    6:
E344: Can't find directory "/private/var/folders/cs/l6c6g06x0974_0w5pdg8dps80000gn/T/vS6Uq6o/4" in cdpath
E472: Command failed
```

There's 2 problems here as I see it:

1. vim-signify isn't realizing that the buffer changed paths (or had its path removed entirely). I'd imagine this may cause other issues too, such as it getting git status for the wrong repo.
2. vim-signify isn't handling chdir errors in `s:run()`.

**Comment by jamessan** [comment]
Are you running with the changes Marco committed in c0da740 and 0867de3?

**Comment by kballard** [comment]
Yes. I filed this report literally 5 minutes after updating the plugin.

**Comment by mhinz** [comment]
> vim-signify isn't realizing that the buffer changed paths (or had its path removed entirely). I'd imagine this may cause other issues too, such as it getting git status for the wrong repo.

This should be fixed now.

> vim-signify isn't handling chdir errors in s:run()

Yes, Sy assumes that during the runtime of `sy#start()` no external process is altering the file. `:chdir` shouldn't fail anymore, since if the file itself is readable, the working directory must be valid, too.

**Comment by mhinz** [comment]
@kballard \**ping*\*

**Comment by kballard** [comment]
@mhinz The specific scenario I originally reproduced this issue with no longer reproduces.

**Comment by mhinz** [comment]
Ah, great.

Thanks for reporting this issue!
