### ISSUE TITLE
signify_vcs_cmds extra args

### ISSUE THREAD

**Issue by patspam** [mhinz/vim-signify#168]
I switched over from vim-gitgutter and am missing the ability to add extra args to the vcs command.

I find this handy for eg. changing which git branch you're diffing against.

eg, With vim-gitgutter, I would type:

    let g:gitgutter_diff_args = 'foo'

..and henceforth diffing would be done against the `foo` branch.

I tried doing this in vim-signify with:

    let g:signify_vcs_cmds['git'] = 'git diff --no-color --no-ext-diff -U0 -- %f foo'

..however `g:signify_vcs_cmds` appears to be cached. Reloading the file and/or running `:SignifyRefresh` didn't help.

**Comment by mhinz** [comment]
Hey, I was on a longer trip, hence the late response.

I'm looking into it.

**Comment by mhinz** [comment]
It should work now, thanks for reporting!

**Comment by patspam** [comment]
Thanks!!

**Comment by mhinz** [comment]
You're welcome!
