### ISSUE TITLE
Enhancements to SignifyFold

### ISSUE THREAD

**Issue by albfan** [mhinz/vim-signify#169]
Using fold on changes is great, feels like you are in front of a unified diff output, but editable. just a few tweaks:

- Using fold seems to use `:only` hidding all other buffers opened
- Activating SignifyToggleHighlight does not refresh colours until you pass cursor from changed lines
- What about `:SignifyToggleFold`. You can use `zR`, `zM` to open close but `zE` doesn't work.

**Comment by mhinz** [comment]
> Using fold seems to use :only hidding all other buffers opened

I'm not sure I'm misunderunderstanding you here, but it simply opens the current file in a new tab.

> Activating SignifyToggleHighlight does not refresh colours until you pass cursor from changed lines

Hmm, true. It used to work at a certain point in time.. I'll look into it. Simply adding a `:redraw!` will work for sure.

> What about :SignifyToggleFold. You can use zR, zM to open close but zE doesn't work.

You cannot close folds if the used folding method is `expr`, like in `:SignifyFold` its case.

**Comment by albfan** [comment]
Thanks! (didn't notice the tab) then would be cool to fold on same buffer.

About toggle folding I mean to remember last foldmethod setup and go back to it, but that only makes sense folding current buffer, not new tab.

**Comment by mhinz** [comment]
@albfan Actually it was done on purpose, since there is (as far as I know) no way to restore manually created folds.

BTW, the `:SignifyToggleHighlight` issue should be fixed now.

**Comment by albfan** [comment]
Great!. Anyway :SignifyFold is terrific!

**Comment by mhinz** [comment]
:-) Thanks for the feedback!
