### ISSUE TITLE
[RFC] How to handle unknown buffers?

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-signify#172]
cc @jamessan

Assuming `g:signify_vcs_list = [ 'git' ]`.

With this setting Sy would run the typical `git diff` line for each new buffer. If the command fails, it means that the buffer isn't handled by git. The buffer is registered as `unknown`. On the next write, we will use `git diff` again and it will fail again, keeping the type as `unknown` and so on. We do this, so we can detect whether the file was added to git during the running Vim instance.

This happens for all files, even those that are never supposed to be handled by a VCS in the first place.

My question: How likely is this case? Should we just set `b:sy.active = 0` if `git diff` fails instead of constantly retrying?

**Comment by jamessan** [comment]
I do run into this all the time, actually, and at work it's particularly painful because accurev is sloooow.

If we had a consistent mechanism to check whether the file was in a version controlled directory, then I would say use that to determine whether to retry.  Since we don't, maybe an option is worthwhile, which defaults to not retrying every time.

**Comment by mhinz** [comment]
I don't think there's a better way for detecting if the file is version-controlled. Just searching for directories like `.git` or `.hg` etc. only says that the directory is a repo but nothing about the current file. (This is the only other option I can think of.)

So.. I guess we agree!

I'll simply register the buffer as not active, when all VCS from `g:signify_vcs_list` fail to return a proper diff. (Or maybe I'll see if I can avoid setting `b:sy` at all in that case.)

Then we could, like you said, introduce an option or just add a command `:SignifyForce` that simply ignore the `b:sy.active` option (or whatever I'll use to denote a non-VCS file), so people can still run Sy without restarting Vim in the unlikely case that a repo was initialized.

**Comment by mhinz** [comment]
Implemented in https://github.com/mhinz/vim-signify/commit/a96f1a7dc740aa35b0372f637198586ad70c5366.
