### ISSUE TITLE
Update signify when using fugitive

### ISSUE THREAD

**Issue by lvwrence** [mhinz/vim-signify#174]
When using fugitive commands like :Gcommit, I don't think signify updates (it stills shows the previous diff, when it should be empty).

**Comment by jamessan** [comment]
The same happens if you commit outside of Vim.  By default, Sy only updates when a buffer is saved.  Calling `:Gcommit` doesn't do anything to trigger Sy to update its notion of what differences there are.  You could try calling `SignifyRefresh` from the `User` autocmd that fugitive defines.

    autocmd User Fugitive SignifyRefresh

**Comment by mhinz** [comment]
@lvwrence *ping*

**Comment by mhinz** [comment]
Please reopen, if this is still an issue.

**Comment by languitar** [comment]
I also stumbled across this issue. On linux, wouldn't it be possible to use inotifywait to detect changes to some git files to provide an auto refresh?

**Comment by mhinz** [comment]
This would need quite a bit of code, written in VimL, only for that specific platform, only if inotifywait is installed, only if the kernel supports it, and only for git? :>

That's a touch too specific and error-prone for my taste.

Is the solution mentioned above not working for you or were you merely suggesting an alternative?

**Comment by languitar** [comment]
It is working for me. However, sometimes I use the shell to do some complex committing and in that case the symbols are not updated. What does gitgutter use to refresh?

**Comment by mhinz** [comment]
Maybe you just want to enable `:h g:signify_update_on_focusgained` instead. Not all terminal emulator handles these the `FocusGained` and `FocusLost` events, though. And if you're using tmux, you might need something like [vim-tmux-focus-events](https://github.com/tmux-plugins/vim-tmux-focus-events) as well.

**Comment by languitar** [comment]
Does this also help in case I use neovim's built-in terminal? Because then vim always had focus.

**Comment by mhinz** [comment]
No. In that case maybe:

```vim
if has('nvim')
  autocmd WinLeave term://* SignifyRefresh
endif
```
