### ISSUE TITLE
custom vcs cmd

### ISSUE THREAD

**Issue by orrsonn** [mhinz/vim-signify#175]
Hi

I am trying to disable whitespace checking in signify
I have following in my vimrc

```
let g:signify_vcs_cmds = { 'git': 'git diff --no-color --no-ext-diff -U0 -w -- %f' }
```

It works, when started the first time and all the other cmds are still set.. 

As soon as I reload the vimrc with ```:so $MYVIMRC``` only the git command is set, all of the other are gone. I am using svn as well and after sourcing vimrc this doesn't work anymore.

Is it possible to set that differently or make it more resilient?

Thank you

**Comment by jamessan** [comment]
Sure, change your vimrc to do this instead:

    if !exists('g:signify_vcs_cmds')
        let g:signify_vcs_cmds = { 'git': 'git diff --no-color --no-ext-diff -U0 -w -- %f' }
    endif

Reloading your vimrc doesn't reload the backfilling that happens in [autoload/sy/repo.vim](https://github.com/mhinz/vim-signify/blob/6333c7f140c3b57cad0881617c07017c59f68220/autoload/sy/repo.vim#L215-L217).

**Comment by orrsonn** [comment]
works. thank you!
