### ISSUE TITLE
No sign for deleted lines at bottom of file

### ISSUE THREAD

**Issue by Grueslayer** [mhinz/vim-signify#178]
If I remove a line at the very end of the file with no further modification on the last available line no sign is displayed.

**Comment by jamessan** [comment]
> remove a line at the very end of the file with no further modification on the last available line

This is a bit confusing.  Do you mean that changing a buffer from

    123
    456
    789

to

    123
    456

doesn't show a sign for you?  Here, I see `_1` (based on the default `g:signify_sign_delete`) in the sign column.

**Comment by Grueslayer** [comment]
That's only for TFS and caused by my stripping code  from #177. I need to fix that.
