### ISSUE TITLE
regexp support to skip files

### ISSUE THREAD

**Issue by nicdumz** [mhinz/vim-signify#179]
Hey!

I would love to be able to skip running signify on temporary files.
They are dropped at the root of the VCS I use, looking like `.someprefixtmp-randomsuffix`

- `g:signify_skip_filetype` is not useful in this case, since ft detection / syntax higlight is useful, and nothing separates those from ordinary, regular files, type-wise.
- `signify_skip_filename` is not helpful, since I need to match a regexp.

Something like `g:signify_skip_filename_pattern = [ '.*\.someprefixtmp.*']` would be great.

Thanks!

**Comment by mhinz** [comment]
@nicdumz Should work now!

**Comment by nicdumz** [comment]
Awesome, thanks!
