### ISSUE TITLE
Disable signs, but NOT disable sy#repo#get_stats()

### ISSUE THREAD

**Issue by mtglsk** [mhinz/vim-signify#181]
Can this be done? I use this plugin primarily to have a nice statusline indicator of changes, Sometimes signs are useful, but sometimes they are distracting. SignifyToggle disables `sy#repo#get_stats()` so i don't get any info in my statusline.

This sort of works: `autocmd BufWritePost            * sign unplace *`, but feels like a hack.

**Comment by mhinz** [comment]
The "status" comes from getting a diff and manually parsing it in VimL. Even if we'd introduce an option like that, all that parsing would happen anyway, only the actual `:sign place` would be guarded by an `:if`. So, performance-wise it wouldn't make a difference. Moreover, It would be easier not to do that for each changed line and just use `:sign unplace *` afterwards.

So, the outcome would be the same. I'd suggest using the autocmd you gave. (I did some quick tests and it seemed to work pretty good.)

p.s. Placed signs are also used for hunk jumping and you can't place signs without showing the sign column.

Nevertheless, thanks for the feedback!

**Comment by jamessan** [comment]
One change that might be worth making is to add `doautocmd User Signify` in relevant places before exiting `sy#start()`.  Then the autocmd could be

```viml
autocmd User Signify call sy#sign#remove_all_signs(bufnr(''))
```

This would help both to avoid running the autocmd for buffers where Sy isn't active and would only remove Sy-specific signs.

**Comment by mhinz** [comment]
:+1:

**Comment by jamessan** [comment]
@mtglsk Take a look at 44a35a7.  I've implemented my earlier suggestion.

@mhinz Mind reviewing the docs?

**Comment by mtglsk** [comment]
Doesn't seem to work for me per example, in fact calling `sy#sign#remove_all_signs(bufnr(''))` directly clears the list from `sy#repo#get_stats()`.

Doing `autocmd User Signify sign unplace *` does work though.

**Comment by jamessan** [comment]
Ah, well you could cache the stats as part of the autocommand, before clearing, but I think that it's probably better to move the stat clearing elsewhere.

`remove_all_the_signs` should just ... remove the signs.

**Comment by jamessan** [comment]
Done in f6e354b.

**Comment by jamessan** [comment]
@mtglsk I've updated the user-autocommand branch.  Once @mhinz reviews the documentation, I plan to merge it.

**Comment by mhinz** [comment]
@jamessan LGTM (although this particular use case will much likely provoke a pesky flicker).

**Comment by jamessan** [comment]
Yeah, but there's not much we can do about that.  The important part is giving the user the ability to do something in reaction to detecting there are uncommitted changes.

I'll merge this later today.
