### ISSUE TITLE
Gutterline color issues

### ISSUE THREAD

**Issue by peteyy** [mhinz/vim-signify#182]
The gutterline's background color does not match my signify symbols background color, any ideas how to fix that?

https://www.dropbox.com/s/dn0pncewu6fff4a/Screenshot%202016-03-29%2010.34.36.png?dl=0

**Comment by jamessan** [comment]
`:help signify-colors`

Define the `SignifySign*` highlight groups to match the coloring you want.

**Comment by RyGuyX** [comment]
That doesn't help and this is still an issue
https://imgur.com/a/DKUDk8Y
