### ISSUE TITLE
E216: No such group or event: <nomodeline> User Signify

### ISSUE THREAD

**Issue by chilicuil** [mhinz/vim-signify#185]
Hello,

After commit https://github.com/mhinz/vim-signify/commit/3f0df1498c02ec8db25e6acf52eac56fc9f98eca every time I open vim with vim-signify enabled I receive the above message, I'm running Vim 7.3.429 which is the default in Ubuntu 12.04. I think the problem could be that the `<nomodeline>` keyword is not supported in the local version, as in https://github.com/tpope/vim-projectionist/issues/7 , could the new code avoid `<nomodeline>`? or only use it when a more up to date vim version is detected?

Thank you for the great plugin!

**Comment by mhinz** [comment]
How unfortunate! `<nomodeline>` was implemented only a few patches later in 7.3.438. But I like to keep the feature anyway.

We could add an old-style condition `v:version >= 704 || (v:version == 703 && has('patch438'))`, but I think just silently ignoring works just as well.

**Comment by mhinz** [comment]
Should be fixed now. Thanks for reporting!
