### ISSUE TITLE
I got some error message, when I use this plugin in win7+gvim.

### ISSUE THREAD

**Issue by wsdjeg** [mhinz/vim-signify#187]
I can not change my vim message language, so the error message is
![qq 20160915190108](https://cloud.githubusercontent.com/assets/13142418/18547596/cf58c5ce-7b76-11e6-8f78-25ef1756480e.png)

here is my debug step:
add `let g:wsdjeg = signlist` after line 27 of autoload/sy/sign.vim.
then `:echo g:wsdjeg` I got
![qq 20160915190842](https://cloud.githubusercontent.com/assets/13142418/18547805/d9f06dce-7b77-11e6-99d0-b5974f3adf37.png)

but in sign.vim
it is `let tokens = matchlist(signline, '\v^\s+line\=(\d+)\s+id\=(\d+)\s+name\=(.*)$')`
so I think maybe it is due to my language setting.

but I have this in my vimrc

``` vim
"Use English for anything in vim
if WINDOWS()
    silent exec 'lan mes en_US.UTF-8'
elseif OSX()
    silent exec 'language en_US'
else
    let s:uname = system("uname -s")
    if s:uname == "Darwin\n"
        " in mac-terminal
        silent exec 'language en_US'
    else
        " in linux-terminal
        silent exec 'language en_US.utf8'
    endif
endif

" try to set encoding to utf-8
if WINDOWS()
    " Be nice and check for multi_byte even if the config requires
    " multi_byte support most of the time
    if has('multi_byte')
        " Windows cmd.exe still uses cp850. If Windows ever moved to
        " Powershell as the primary terminal, this would be utf-8
        set termencoding=cp850
        " Let Vim use utf-8 internally, because many scripts require this
        set encoding=utf-8
        setglobal fileencoding=utf-8
        " Windows has traditionally used cp1252, so it's probably wise to
        " fallback into cp1252 instead of eg. iso-8859-15.
        " Newer Windows files might contain utf-8 or utf-16 LE so we might
        " want to try them first.
        set fileencodings=ucs-bom,utf-8,utf-16le,cp1252,iso-8859-15
    endif

else
    " set default encoding to utf-8
    set encoding=utf-8
    set termencoding=utf-8
endif
set langmenu=en_US
let $LANG = 'en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
```

**Comment by jamessan** [comment]
> I can not change my vim message language

Why not?  You're saying that if you execute

```vim
lang message
lang message C
lang message
```

that it will report the same value for the message language both times, instead of reporting C the second time?

**Comment by mhinz** [comment]
@wsdjeg ^

**Comment by mhinz** [comment]
Well, this needs to be fixed in Vim. :-) Closing.

**Comment by wsdjeg** [comment]
yeah!

**Comment by Jerry-Ma** [comment]
Hi,

I am experiencing similar error when using this plugin with neovim  on the latest OS X. The error message is about "language message C" command is not available in this version of vim. I directly type :language message C in a nevoid session, and it gives the same error. I tried the same command on my fedora machine, it successfully returns the locales.

**Comment by mhinz** [comment]
@Jerry-Ma 

Could you paste the output for `:language message C` and `:language message` in Neovim?

**Comment by Jerry-Ma** [comment]
@mhinz 

> Could you paste the output for :language message C
 E319: The command is not available in this version

>  and :language message in Neovim?
 E319: The command is not available in this version

> What's "nevoid"? Does it happen outside a nevoid session as well?
 It was a typo. I meant neovim.

**Comment by mhinz** [comment]
Hmm, apparently [HAVE_WORKING_LIBINTL](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds2.c#L3478) wasn't set, when Neovim was build.

What Neovim version and OS are you using?

**Comment by Jerry-Ma** [comment]
```
❯ nvim -v
NVIM v0.2.0-96-g29e6515
Build type: Debug
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/ma/Applications/neovim/build/config -I/Users/ma/Applications/neovim/src -I/Users/ma/Applications/neovim/.deps/usr/include -I/Users/ma/Applications/neovim/.deps/usr/include -I/Users/ma/Applications/neovim/.deps/usr/include -I/Users/ma/Applications/neovim/.deps/usr/include -I/Users/ma/Applications/neovim/.deps/usr/include -I/Users/ma/Applications/neovim/.deps/usr/include -I/usr/include -I/Users/ma/Applications/neovim/build/src/nvim/auto -I/Users/ma/Applications/neovim/build/include
Compiled by ma@mbp-ma.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
```

```
❯ uname -a
Darwin ma-mbp.local 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64
```

```
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2659
```

**Comment by Jerry-Ma** [comment]
@mhinz 

With the hint you gave, I was able to get everything working by installing gettext using homebrew and rebuilding neovim. Thank you for the help!

**Comment by mhinz** [comment]
@Jerry-Ma 

Even better! The commit above makes Sy not rely on `:language` anymore. So we avoid the issue entirely.
