### ISSUE TITLE
Make plugin async

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-signify#201]
This should make the plugin _feel_ more snappy and also avoids the typical `cmd.exe` flash when using `system()` on Windows (Ref: https://github.com/mhinz/vim-signify/pull/196).

**Comment by skywind3000** [comment]
Wish I can use it as soon as possible. 
Vim-signify can be as smooth as similar packages in emacs if it can be implemented.

and you will make vim great again

**Comment by mhinz** [comment]
I started implementing async support in #203.
