### ISSUE TITLE
How to swap LineNr and SignColumn ?

### ISSUE THREAD

**Issue by gigi206** [mhinz/vim-signify#202]
Hello,

First, thank you for your job :)

Is it possible to swap LineNr and SignColumn ?

Also I use NeoBundle :
`NeoBundleLazy 'mhinz/vim-signify', {'autoload' : {'commands' : ['SignifyToggle']}}`

When I load the plugin in lazy mode, colors are not taken into account in my vimrc for exemple :
`highlight SignColumn ctermbg=Black`

Thanks

**Comment by gigi206** [comment]
For the NeoBundleLazy it's ok, I have multiple vimrc and I haven't edited the good one...

Sorry for the mistake.

Just the main problem, how to swap the 2 columns :)

**Comment by mhinz** [comment]
Hi,

Unfortunately there's nothing we can do about it. It's a Vim thing. It knows 3 kinds of special columns:

- fold column
- number column
- sign column

And those are kind of hardwired in the code. :-)

**Comment by gigi206** [comment]
Thank you for your reply 🙂
