### ISSUE TITLE
Error in vim: E118: Too many arguments for function: sy#repo#get_diff_rcs  

### ISSUE THREAD

**Issue by wimstefan** [mhinz/vim-signify#205]
Since I've updated signify today I get the following message in vim:
```
Error detected while processing function <SNR>96_callback_exit:
line    3: 
E118: Too many arguments for function: sy#repo#get_diff_rcs
Error detected while processing function <SNR>96_callback_exit[3]..sy#repo#get_diff_cvs:
line    2: 
E691: Can only compare List with List
E15: Invalid expression: ((a:exitval == 1) && (a:diff =~ '+++')) ? [1, diff] : [0, '']
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 22 2017 23:16:26)
Included patches: 1-222
Modified by Gentoo-9999

```g:signify_vcs_list``` is empty.

**Comment by mhinz** [comment]
Stupid error, but easy to fix. Thanks for reporting!

**Comment by wimstefan** [comment]
I'm sorry but I still get an error after updating ...

```
Error detected while processing function <SNR>91_callback_exit[3]..sy#repo#get_diff_cvs:
line    2:
E691: Can only compare List with List
E15: Invalid expression: ((a:exitval == 1) && (a:diff =~ '+++')) ? [1, diff] : [0, '']
```

**Comment by mhinz** [comment]
Just today I merged a rather big PR which changed Sy to use Vim 8's and Neovim's async features. Unfortunately merging such PRs into master seems to be the best way to get good feedback for these kind of repos.

So, sorry for the inconvenience, but all the small potential issues should be fixed quite soon.

**Comment by wimstefan** [comment]
Nothing but praise here! :sunglasses: 

I noticed the big PR and the only thing I could do was reporting some minor glitches. You're doing the hard work and you do it fantastic! Thanks a lot :smile:
