### ISSUE TITLE
error: E121: Undefined variable: b:sy

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-signify#207]
After using `ZQ` to close a buffer/window showing a file in the git repo, the next focused window/buffer was showing a git diff (i.e., not a file that's part of the git repo). This error occurred:

```
Error detected while processing function <SNR>100_callback_exit[3]..sy#repo#get_diff_git[3]..<SNR>100_get_diff_end:
line    3:
E121: Undefined variable: b:sy
```

**Comment by mhinz** [comment]
I actually can reproduce it with `ZZ`, because it's a race condition. I'll pass the buffer number to the job as well to make sure it still exists when the exit handler is run.

**Comment by mhinz** [comment]
Thanks!
