### ISSUE TITLE
SignifyRefresh does not preserve cursor / current window

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-signify#209]
With several windows open, `SignifyRefresh` command may leave the cursor in the wrong window.

**Comment by jamessan** [comment]
Hmm, [sy#util#refresh_windows] does save/restore the focused window, but you're right that the cursor ends up somewhere else.

[sy#util#refresh_windows]: https://github.com/mhinz/vim-signify/blob/f7678884f0f6b559df8b993192834ef7953c4880/autoload/sy/util.vim#L25-L40

**Comment by jamessan** [comment]
Even worse, the signs are lost.

**Comment by mhinz** [comment]
Hmm, I see that the `win_getid()`/`win_gotoid()` isn't working for some reason. (But signs are not lost in the tests.)

Since `:windo` doesn't change tabs and the window numer is expected to stay the same, the old `winnr()`/`:wincmd w` way should be good enough anyway. And that one seems to always work.

**Comment by mhinz** [comment]
@jamessan  I think the disappearing signs bug should be fixed now: https://github.com/mhinz/vim-signify/commit/68013238b4f891cdd485aa8e17ddfed6b320d728

**Comment by mhinz** [comment]
The `win_gotoid()` in `sy#util#refresh_windows()` works as expected, it's just that it's highly likely that refreshing the signs in the last window also means `callback_exit()` is run last in that window. And that function switches the window as well: https://github.com/mhinz/vim-signify/blob/master/autoload/sy/repo.vim#L42

**Comment by jamessan** [comment]
Why is `callback_exit()` restoring the window?  That's the wrong place to have the logic, since it's async.

**Comment by mhinz** [comment]
I guess the logic was that the user could have switched windows after doing `:w` but before the external command retruns. But since `:sign place` takes bufnums as well and not only works for the current buffer.. yes, it should be left away.

**Comment by mhinz** [comment]
@justinmk Should be fixed on master now.
