### ISSUE TITLE
TFS broken

### ISSUE THREAD

**Issue by Grueslayer** [mhinz/vim-signify#211]
Hi,

TFS does not work since introducing the new sy#repo#get_diff_ function arguments. The "a:diff" argument is not the file content with line feeds anymore, instead it is an array of lines.

The strip_context function needs some fixes:

~~~diff
--- repo.orig	2017-01-31 07:22:23.334755300 +0100
+++ repo.vim	2017-01-31 07:46:45.890564200 +0100
@@ -283,7 +283,7 @@
   let diff = []
   let hunk = []
   let state = 0
-  let lines = split(a:context,"\n",1)
+  let lines = a:context
   let linenr = 0
 
   while linenr < len(lines)
@@ -356,7 +356,7 @@
     let diff = diff + hunk
     let hunk = []
   endif
-  return join(diff,"\n")."\n"
+  return diff
 endfunction
 
 " Variables {{{1
~~~

**Comment by mhinz** [comment]
Ah, yes. The type changed when we made Sy asynchronous, because the callback handler get lists of strings opposed to a single string that `system()` would return.

Thanks!
