### ISSUE TITLE
Error E119 function sy#repo#get_diff_git has not enough argument

### ISSUE THREAD

**Issue by mmassaro** [mhinz/vim-signify#212]
Hello,

when I open an existing file, I have the following error (in french)

> Erreur détectée en traitant function sy#start[39]..sy#repo#detect[13]..sy#repo#get_diff_start :
> ligne 46:
> E119: La fonction sy#repo#get_diff_git n'a pas reçu assez d'arguments

The last line means that the function sy#repo#get_diff_git has not enough arguments.

This error occurs before and after the fix of @Grueslayer.

**Comment by mhinz** [comment]
Ah, thank you!
