### ISSUE TITLE
Problem with <plug>(signify-next-hunk)

### ISSUE THREAD

**Issue by teto** [mhinz/vim-signify#215]
If I try:
`nmap <leader>wj <plug>(signify-next-hunk)` 
then I endup in insert mode and I don't go to the next hunk.

I've tried debugging this with a MWE but then everything works.

If in vim-signify, I replace the  <plug>(signify-next-hunk) definition by
`nnoremap <silent> <plug>(signify-next-hunk) :call sy#jump#next_hunk(v:count1)<cr>`
it works with my full config. So I suspect there is some bad interaction with other plugins because of the expression :
```
nnoremap <silent> <expr> <plug>(signify-next-hunk) &diff
      \ ? ']c'
      \ : ":\<c-u>call sy#jump#next_hunk(v:count1)\<cr>"
```
yet I can't see how ? any idea ?
Neovim `echo &diff` returns 0.

**Comment by mhinz** [comment]
1. Is `:verb nmap <leader>w` showing anything suspicious?
1. What is a "MWE"?

**Comment by teto** [comment]
I confirm for MWE. I try to never use acronyms but this one is shared by many vim plugins authors so ^^
The problem is too strange and as it works with a MWE, it should be my config. For now I will :call sy#jump#next_hunk(v:count1)<cr>, I am not a fan of debugging vimscript. 
Sorry for the noise
