### ISSUE TITLE
Only last hunk signified

### ISSUE THREAD

**Issue by Krakonos** [mhinz/vim-signify#218]
Hi! I've been using signify plugin (latest git version) for ages, but recently switched to neovim (0.1.7) and found a problem. In a file (tracked using mercurial), only last hunk shows as difference. The `:SignifyDebug` shows all my changes, so does running signify in vim8. Running `:SignifyRefresh` or `:SignifyToggle` doesn't change that. 

This problem only happens on a single file and I tried it on some others in the same repository or other repositories, and couldn't reproduce the problem.

Unfortunately, I can't share the repository and files, however, I'd be happy to help with debugging. I will be watching closely if I ever find it on another file. Any ideas on what could be wrong?

**Comment by mhinz** [comment]
Hmm, as you can imagine, it's really hard to debug that way. ;-)

Okay.. it works in Vim 8 and even with Neovim 0.1.7 `:SignifyDebug` shows a proper diff.

1. Can you confirm that `:SignifyList` for that buffer contains a hunk for the lines where the sign is missing?
2. Is the hunk at the very start or end of the file? Or are there _lots_ of changes? Anything that could be an edge case compared to the other files in the repo that work?
3. It would be interesting to know if it still happens with Neovim master, since v0.1.7 is over 500 commit ago already.

**Comment by Krakonos** [comment]
I'm aware, and it's great you're willing to help!

1) If I read the output correctly, it only contains the one shown change (lines 448+). I'm not sure what the IDs are. See the output below.
2) It's at the very end of file, only a few changes (approxi 10-15 hunks). I tried replicating this on another files, but without success.
3) I just tried with eaf9caaf43516366e8d8aa44185f13079649ac59, same behavior.


```
    active  =  1                                                                                                                                                                                                                                                                                                               
    buffer  =  1                                                                                                                                                                                                                                                                                                               
       vcs  =  hg                                                                                                                                                                                                                                                                                                              
     stats  =  18 added, 0 changed, 0 removed                                                                                                                                                                                                                                                                                  
    signid  =  274                                                                                                                                                                                                                                                                                                             
     hunks  =  start: 448, end: 465, IDs: [256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273]        
```

**Comment by mhinz** [comment]
So I created a hg repo, added a file with 447 random lines, committed.

Now, when I add 18 lines below it, I get _exactly_ the same `:SignifyList` output. (Every sign has an ID, so those are the IDs for each line in the hunk.)

But I also get `+` sign for each line, even with Neovim v0.1.7 and master.

Could you try a minimal vimrc? (So, comment out (or use `:finish`) most of your settings and especially most of your plugins. Maybe it's another plugin that is interfering.)

**Comment by Krakonos** [comment]
So in my case, I do have signs for the last hunk (448+), but any change before that. I have all kinds of changes: added, removed or changed lines. The next-to-last hunk doesn't seem to matter, I've tried a few modifications and it's currently almost the same as the last one. Deleting the added lines in the last hunk (removing it from the diff) results in a "clean" file, without any signs.

I've tried with clean config. I made another user, installed Vundle and Signify, the results are exactly same.

**Comment by mhinz** [comment]
Oh, so the hunk is shown properly, but the problem is that it's the only hunk picked up.. now that's strange.

Usually Sy works asynchronously on Neovim and newer Vim versions, but `:SignifyDebug` is forced to run synchronously. Maybe that's a hint that the async callback handler from Neovim doesn't provide all the data for some reason.

Please add the following below [this line](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/repo.vim#L46):

```vim
  for line in self.stdoutbuf | echomsg line | endfor
```

Afterwards open the buffer with the missing hunks again and check that output of `:messages`. Is it showing a correct diff? Are there multiple hunks (lines starting with `@@`)?

**Comment by Krakonos** [comment]
There is a single hunk starting with `@@` and a piece of a previous one, but it seems to be missing it's header. Roughly like this;

```
diff xx yy
--- a
+++b
+ stuff
+ more
+ even more ...
+ [...]
+ but nothing marked in vim
@@ -377,0 +448,18
+ more stuff here
+ this is the hunk correctly marked
+ [...]
```

**Comment by mhinz** [comment]
There you go. That shouldn't be happening. :->

Now, does manually running `hg diff` in the shell include the missing hunks? (The exact command used is `:echo b:sy_info.cmd`.)

**Comment by Krakonos** [comment]
I'll check tomorrow once I get back to work. I tried a similar command, which worked fine. I think we're getting close to the culprit!

**Comment by Krakonos** [comment]
I'm back at work, debugging. I tried the command returned by b:sy_info.cmd and it returns the complete diff, still I have only tha partial diff in "messages". As there are exactly 40 lines in the partial diff, I tried making diff large enough to add more than 40 lines, without any results -- all other files still behave right.

For a while, I suspected some unusual character could have lurked inside, but didn't find one and joining the first line in my incomplete hunk and the previous one resulted in the joined line being in the hunk, again resulting in 40 lines of diff.

**Comment by Krakonos** [comment]
Progress! I've just deleted 3 lines added to my code much earlier, and now everything is working. They were 3 lines in their own hunk, all added. Adding them back breaks it again, removing them fixes the issue. Removing one or two of them has no effect, only the complete hunk has to be removed. I'll mail you two diffs of that file in hopes you can find out why.

**Comment by mhinz** [comment]
Hmm, I can't see anything special in that offending hunk.

Could you please add another debug line below [here](https://github.com/mhinz/vim-signify/blob/a2c28f654087735a276ec7c1f558b782db5488a5/autoload/sy/repo.vim#L24):

```vim
  if string(a:data) =~ '@@' | echomsg 'DEBUG: '. string(a:data) | endif
```

Same game. Open buffer, check `:messages`. I'd like to be sure that it's not just a wrong logic in the stdout handler. (Read: All `@@` lines appear, but for some reason don't get added to `stdoutbuf`.)

**Comment by Krakonos** [comment]
1. I sent you the data. There is something strange, as I get two DEBUG: outputs instead of one.
2. No, deleting the lines before the offending hunk doesn't fix it, or changes behavior much.

**Comment by Krakonos** [comment]
So, I've been digging a bit a found another repo of mine showing the same problems. It indeed seems to be a problem in large diffs.
```
git clone https://github.com/openstreetmap/merkaartor.git
git checkout 7efdb09f
git reset  7efdb09f~1
nvim translations/merkaartor_id_ID.ts
```
In git there are changes all over the file "for example, see the line with "Merkaartor version", but only last few changes are signified. Hope it helps in debugging!

**Comment by mhinz** [comment]
Awesome, we can easily reproduce it with that repo. I'll keep you updated. Thanks for the feedback so far!

**Comment by mhinz** [comment]
Oh man.. this was the most embarrassing bug. A typo so evil that I wonder how the plugin worked at all.

It should be fixed now on master.

**Comment by Krakonos** [comment]
Confirmed, master works perfectly. Thanks for your help and the fix!

**Comment by mhinz** [comment]
And thank your for your useful and precise responses. Made it much easier to track down this bug! :+1:
