### ISSUE TITLE
No changes shown

### ISSUE THREAD

**Issue by fraenkel** [mhinz/vim-signify#219]
I am on the v1.9 release using vim 8.
I am noticing random behavior but I think I see the pattern.
Some of my files will show changes and others will not but eventually they will all show no changes.

It looks like the pathing to the file is not correct. At some point it has the fully qualified path to the file and then eventually it switches to a relative path or just the filename itself. The PWD is a some directory above the file but rarely the directory of the file.

SignifyDebug shows the correct diff but SignifyList shows no changes.

**Comment by mhinz** [comment]
Which VCS?

**Comment by fraenkel** [comment]
Git

**Comment by mhinz** [comment]
Wait, if you have a `:SignifyList`, then you're probably on master not on the v1.9 release, right?

**Comment by fraenkel** [comment]
My screwup. All fixed now.
