### ISSUE TITLE
toggle lines highlight vs signs

### ISSUE THREAD

**Issue by unphased** [mhinz/vim-signify#220]
I'd like to make a bind that toggles showing add/remove highlight styles in-line, and this works, but I can't seem to find an option for signify that lets me disable the signs and remove the signs. I can remove the signs but they instantly come back. 

I understand that the original purpose of the plugin was to make the signs and maybe for now it just tends to always put the signs back on.

**Comment by mhinz** [comment]
I'm not sure I understand, but if you want line highlighting without signs, then that won't be possible. The highlighting relies on signs being set. That's a Vim thing and nothing I can do about.

**Comment by unphased** [comment]
OK thats fine then if its a limitation. 

Yeah I figure if i'm gonna make it drastic enough to color the lines that i could at least hide the signs. But at any rate the highlighting would be a bit limited for showing what happens for removal anyway. I just remember a feature in Visual Studio that I used a while ago where you edit the doc and it displays a diff live. I would die of happiness if Vim could eventually do this.

**Comment by jamessan** [comment]
For what it's worth, if you're using a new enough (n)vim, then you can simply `:set signcolumn=no` to not show the sign column at all, even when signs are configured.

**Comment by mhinz** [comment]
@jamessan Oh, wow. I missed that recent change. That's very cool!

**Comment by unphased** [comment]
whoa thanks for the tip. I might use it for this.....

**Comment by mhinz** [comment]
It's not even _that_ recent: [helpful.vim](https://github.com/tweekmonster/helpful.vim) says 7.4.2001. Considering that most people switched to Vim 8 (or Neovim) already.. Nice change.

**Comment by unphased** [comment]
been modernizing my vim today. somewhere between earlier 7.4 and recent 8.0 vim has also gained 24-bit gui color for terminal. My vim is frickin beautiful now...
