### ISSUE TITLE
Error: Using a Job as a Number

### ISSUE THREAD

**Issue by chocoelho** [mhinz/vim-signify#222]
I've recently updated my Vim from 7.4 to 8 in Linux Mint and started receiving this error message:

```
Error detected while processing function sy#start[57]..sy#repo#get_diff_start:
line 25:
E910: Using a Job as a Number
```

How can I do to solve it? I'm using the latest version of `vim-signify` and Vim version is 8.0.0329.

**Comment by mhinz** [comment]
Hmm, yea. The problem happened because Vim uses `Job` objects instead of simply using job IDs like Neovim.

Should be fixed now!

**Comment by chocoelho** [comment]
Awesome! It's been fixed :+1:

**Comment by mhinz** [comment]
Nice, thanks for reporting this!
