### ISSUE TITLE
Slow startup with plugin enabled

### ISSUE THREAD

**Issue by vigilancer** [mhinz/vim-signify#224]
Hi, 
I recently updated my plugins with Vundle and started to experience slow startup time about 8 sec. Before that it took less than a second.
After profiling I found out about 6 sec goes to buffer creating.
After some poking around vim config it seems that reason of slowdown is vim-signify.
Last time I updated plugins was month ago - 18 january.
So it seems to be regression for last month.

% vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 25 2016 22:36:53)
Included patches: 1-1467
Compiled by _pbuild@amd64-1.ports.openbsd.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +title
+cindent         -hangul_input    +netbeans_intg   -toolbar
-clientserver    +iconv           +packages        +user_commands
-clipboard       +insert_expand   +path_extra      +vertsplit
+cmdline_compl   +job             +perl            +virtualedit
+cmdline_hist    +jumplist        +persistent_undo +visual
+cmdline_info    +keymap          +postscript      +visualextra
+comments        +langmap         +printer         +viminfo
+conceal         +libcall         +profile         +vreplace
+cryptv          +linebreak       +python          +wildignore
+cscope          +lispindent      -python3         +wildmenu
+cursorbind      +listcmds        +quickfix        +windows
+cursorshape     +localmap        +reltime         +writebackup
+dialog_con      -lua             +rightleft       -X11
+diff            +menu            +ruby            -xfontset
+digraphs        +mksession       +scrollbind      -xim
-dnd             +modify_fname    +signs           -xsmp
-ebcdic          +mouse           +smartindent     -xterm_clipboard
+emacs_tags      -mouseshape      +startuptime     -xterm_save
+eval            +mouse_dec       +statusline      -xpm
+ex_extra        -mouse_gpm       -sun_workshop    
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: cc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/local/include  -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: cc   -L. -L/usr/local/lib -Wl,-E -Wl,-R/usr/libdata/perl5/amd64-openbsd/5.20.3/CORE  -L/usr/local/lib -Wl,--as-needed -o vim               -lm   -lcurses -liconv -lintl      -Wl,-R/usr/libdata/perl5/amd64-openbsd/5.20.3/CORE -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/libdata/perl5/amd64-openbsd/5.20.3/CORE -lperl -lpthread -lm -lc  -L/usr/local/lib/python2.7/config -lpython2.7 -lpthread -lutil -lm -Wl,--export-dynamic      -Wl,-R -Wl,/usr/local/lib -L/usr/local/lib -lruby18 -lm  -L/usr/local/lib

**Comment by vigilancer** [comment]
seems like 0db69f4658704ff6ddbc69df6be36ec43416044a is the nearest commit that work for me without errors and has slow startup time

commit 31d4c5518 gives me error on startup, no slowdown.
```
"~/.vimrc" 178L, 4479C                                                               
Error detected while processing function sy#start[47]..sy#repo#detect[13]..sy#repo#ge
t_diff_start:                                                                        
line   10:                                                                           
E706: Variable type mismatch for: cmd 
```

**Comment by mhinz** [comment]
> I recently updated my plugins

Define "recently". Are you using the latest commit of vim-signify?

Which VCS are you using in this case? 

> After profiling I found out about 6 sec goes to buffer creating

Using `:profile`? If so, I'd like to see its output so I know where the time is spent exactly. For starters: https://github.com/mhinz/vim-galore/#profiling-at-runtime.

**Comment by vigilancer** [comment]
I meant today, sorry.
I'm updating plugins with Vundle, it's fetching last version from github/vimscripts/whatever.

```
guice% cd ~/.vim/bundle/vim-signify 
guice% git log -1
commit 34ee12d1797091b41bcc9ee3fc655c2a69fce9b0
Author: Marco Hinz <mh.codebro@gmail.com>
Date:   Fri Feb 17 16:25:00 2017 +0100

    Vim compat fix: type variables were introduced in 7.4.2071
    
    To avoid issues for Vim versions between 7.4.1966 and 7.4.2071, we now use
    type() to distinguish between the type of variable `job_id` being either Number
    or Job.
```

**Comment by mhinz** [comment]
What about the other questions? :)

**Comment by vigilancer** [comment]
I was profiling with `--startuptime` - disabling plugins to find one causing an issue.
Also, it is slow only when opening file (3rd log), without arguments (first two logs) no freezes on start.

`vim --startuptime /tmp/vim-startuptime-noargs-q.log +q`
http://pastebin.com/0DEhPHtG

`vim --startuptime /tmp/vim-startuptime-noargs.log`
http://pastebin.com/WKWFffiS

`vim ~/.vimrc --startuptime /tmp/vim-startuptime.log`
http://pastebin.com/0i086L8P

```
guice% vim ~/.vimrc
:profile start /tmp/profile.log
:profile file *
:profile func *
:q
```
http://pastebin.com/umAFpaXs

**Comment by vigilancer** [comment]
With signify disabled:
`vim ~/.vimrc --startuptime /tmp/vim-startuptime-vimrc-wo-signify.log`
http://pastebin.com/xZj8KKku

**Comment by mhinz** [comment]
Oh, maybe I misread what the actual problem is. It's only the startup that is slow? Afterwards updating signs works as fast as expected?

Does it help if you set `let g:signify_vcs_list = ['git']` (or whatever VCS you use) in your vimrc?

**Comment by vigilancer** [comment]
1. Well, I've updated plugins, found problem and fixed it, not sure about signs and all since disabled plugin for now. But .vimrc and other files I've tried was not under VCS control.

```
guice% cd ~/
guice% ls -la ~/.vimrc
-rw-r--r--  1 XXX  XXX  4480 Feb 18 16:23 /home/XXX/.vimrc
guice% git st         
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by mhinz** [comment]
As the documentation points out, you should _always_ set `g:signify_vcs_list`. `:h g:signify_vcs_list` explains why and how it can lead to long delays if you're opening a file that is not managed by a VCS.

The effect is multiple times worse in your case, since you're using a Vim that doesn't support asynchronous execution yet. Updating your Vim will most probably help a lot in this case. But still, setting `g:signify_vcs_list` is a must.

**Comment by vigilancer** [comment]
I see. Seems strange that I hadn't experiencing any delays last month.
Sadly upgrading not an option for me right now.
I understand the motivation, but when disabling some VCSs one have to remember to enable them when times come. Not sure if I'll remember about this option after a while :) Seems that's the way how things work.
Alrighty then, thanks for your time.
