### ISSUE TITLE
Signify settings having no effect

### ISSUE THREAD

**Issue by ddickstein** [mhinz/vim-signify#225]
I'm probably doing something dumb.  I have the following lines in my vimrc:

```
let g:signify_vcs_list = [ 'hg', 'git' ]
let g:signify_sign_show_count = 0
let g:signify_sign_show_text = 0
let g:signify_sign_change = '~'
```

Signify commands, e.g. `:SignifyToggle`, work as expected, and Signify in general works, but these settings aren't respected - text still appears and there are no sign differences (ideally I don't want text to appear but when it was I at least wanted ~ instead of ! (hence that last setting) but that didn't work either.  Sourcing vimrc isn't helping.

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 10 2014 06:55:55)
Included patches: 1-160
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```

**Comment by mhinz** [comment]
Hmm, each of these 3 options alone and in combination work for me. I tested this on Neovim, Vim 8 and Vim 7.4.898.

Your Vim 7.4.160 is _really_ old. Even Debian stable has a newer version. Testing this with a newer version would be nice, I doubt it's the actual issue though.

I can't see any way, how an option like `g:signify_sign_change` wouldn't be respected. What's the output of `:echo g:signify_sign_change`?

**Comment by ddickstein** [comment]
So it seems that the issue was that I needed to actually quit and reload Vim for the settings to take effect; sourcing vimrc was not enough.

**Comment by mhinz** [comment]
Oh, yes. That's the case for a lot of problems, because sometimes it's easier to read in the configuration when the plugin gets sourced and set an internal variable.

Since a lot of plugins do that, restarting Vim is always suggested after changing options.. just to be on the safe side. :)
