### ISSUE TITLE
stale signs after fugitive :Gdiff

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-signify#226]
Steps to reproduce:

```
nvim -u NORC -N +':set runtimepath+=~/.local/share/nvim/bundle/vim-signify/' +':set runtimepath+=~/.local/share/nvim/bundle/vim-fugitive/

:edit <some file in git repo>
:Gdiff
dd " delete some lines in the `.git//0/...` buffer
:write " save the `.git//0/...` buffer
ZQ " close the `.git//0/` buffer
```

Now the original buffer is the only buffer, and its signs are outdated. `:SignifyRefresh` fixes it, but would be nice if the user didn't have to set up autocmds, signify should automatically refresh as appropriate.

**Comment by mhinz** [comment]
Please update Sy and use `let g:signify_realtime = 1`. :)

**Comment by justinmk** [comment]
This is hugely helpful, works much better. Users will appreciate this, do the bold thing and enable it by default :) Otherwise the async support is less valuable. 

I still found one case where it doesn't work: instead of closing the window with ZQ, switch to the window and use `<C-W><C-O>`.

**Comment by mhinz** [comment]
> I still found one case where it doesn't work: instead of closing the window with ZQ, switch to the window and use <C-W><C-O>.

Since there's no event that fires on `:only`, I guess there's nothing I can do about it. :<

**Comment by justinmk** [comment]
Hooking into ShellCmdPost could help, possibly eliminating the need for other hooks.

**Comment by mhinz** [comment]
I don't get it. How is `ShellCmdPost` supposed to help with `<c-w><c-o>` or replace any of the other hooks?

**Comment by jamessan** [comment]
Isn't the problem that whatever you're doing in the fugitive window is changing what content is staged?  That won't be detected by `ShellCmdPost`.

**Comment by mhinz** [comment]
Yea, basically we have to distinguish these situations:

1. We open a buffer: `BufRead` (`g:signify_realtime = 0`) or `BufEnter` (`g:signify_realtime = 1`).
1. The actual file changes (from the inside or outside): `BufWritePost`, `CursorHold`, `CursorHoldI`, `FocusGained`.
1. For a few special situations we also run on `BufEnter`/`WinEnter` to cover things like this `:Gdiff` issue. This is more or less a fallback.. but since it's async, it shouldn't really hurt.

**Comment by jamessan** [comment]
Nevermind my comment. I was confusing `ShellCmdPost` and `FileChangedShell`.  `ShellCmdPost` would be useful if the command affected the staged contents.

**Comment by justinmk** [comment]
ShellCmdPost is just a general suggestion, not specific for Gdiff. It could help with Gstatus though.

> The buffer changes: CursorHold, CursorHoldI (needs a write)

It doesn't make sense for signify to _ever_ auto-save the buffer. Any user that wants autosave will have _already_ set 'autowrite'. Any user that _doesn't_ set 'autowrite' clearly _does not_ want buffers to be auto-saved.

If signify can just avoid the urge to solve (2), the other improvements (1, 3, 4) could be made default: improving things silently for everyone, at no cost. No extra option needed.

**Comment by mhinz** [comment]
I like the idea of always running Sy on `CursorHold` and `CursorHoldI` if `&autowrite` is set, as long as it gets documented. Then we could remove `g:signify_cursorhold` and `g:signify_cursorhold_insert`.

But I'm still not fully convinced that doing the other things by default comes at no cost. The user might not notice it, but it potentally runs the VCS very often (e.g. when switching through buffers), although it might not be needed.

@jamessan What do you think?

**Comment by mhinz** [comment]
Okay, the cursorhold options were removed and fire by default if `'autowrite'` is set.
