### ISSUE TITLE
Do not save file on autocmd CursorHold,CursorHoldI even if autowrite setted.

### ISSUE THREAD

**Issue by wsdjeg** [mhinz/vim-signify#230]
I like this plugin, but here is an issue:
I use vim with autowirte option, this option help me auto save file on some command, but I do not think signify should use this option to write file.
here is a case:

1. Open a file , goto insert mode , type into some code.
2. goto normal mode or still in insert mode, now I want to check the code I am wirte, and I am readding code, so I do not move cursor, but this plugin just write the code to my file.
3. I think another option should be better, such as `g:signify_autowrite_onCursorHold`.

**Comment by mhinz** [comment]
But what's the problem with saving and Sy updating the signs in the background?

**Comment by wsdjeg** [comment]
when I edit a file, sometime I will stop here to check if I type some wrong word, but now I do not want to save file, it will change my undo tree.

when should save happend?
1. run make command, then I am sure I have finish editting.
I think it is better call save(), just on `bufwrite` autocmd,  then if the user set autowrite, I think Sy also will update sign.

**Comment by wsdjeg** [comment]
and I like `autosave` option, It will auto save my file on some command, but now I can not use this option with the plugin.

**Comment by simonsmith** [comment]
Hey,

I've just noticed my Vim is saving my buffers when I exit Insert mode and tracked it down to `vim-signify`. Is this an intentional change? Can I disable it?

Thanks

**Comment by wsdjeg** [comment]
@simonsmith  it is 
https://github.com/mhinz/vim-signify/blob/63efffcae761aeaa05f22b933ec3e487aef7de56/plugin/signify.vim#L27

**Comment by simonsmith** [comment]
Thanks @wsdjeg 

> The reasoning for this change was: When you set 'autowrite', you're willed to save on a lot of occasions anyway.

I can see the logic in that idea. For me the problem is when you're half way through refactoring and change modes it will save the buffer and trigger all kind of linting errors in Neomake/Syntastic.

I've disabled `autowrite` for now :)

**Comment by mhinz** [comment]
I hear you. I'll revert the change that removed `g:signify_cursorhold_normal` and `g:signify_cursorhold_insert` with some slight changes.

They will be implied by `g:signify_realtime = 1`, as long as they don't get explicitly disabled.

With `g:signify_realtime = 0` (the default), they won't be enabled by default.

**Comment by simonsmith** [comment]
🎉 

Great stuff. Thanks for all your work on this plugin

**Comment by mhinz** [comment]
Okay, I re-added the options!

> Great stuff. Thanks for all your work on this plugin

As long as people keep on using this plugin, I'll also maintain it. :-)

Thanks for the feedback!

**Comment by justinmk** [comment]
Another reason that auto-save is destruction is it modifies the `'[` and `']` marks. It shouldn't be the default, even if `g:signify_realtime=1`. Signify never required micro-management, now it does.

**Comment by mhinz** [comment]
@justinmk 

It never saved by default. If you wanted it to do so, you had to enable certain options.

`g:signify_realtime` basically enables lots of things by default and then you can still disable the bits you don't like. Everything is clearly documented. Or you keep disabled and just enable the bits you want.

That's purely subjective. There's not more or less management to do than before the recent changes.

**Comment by justinmk** [comment]
Yeah, I'm wrong that it requires micro-management. Nothing changed compared to before. Rather, for users to _gain_ anything from the recent refactor, they have a big menu to sort through, and compromises to weigh.

**Comment by endersstocker** [comment]
`g:signify_realtime = 1` is auto-saving, much to my dismay, even though I have autowrite disabled.

**Comment by mhinz** [comment]
This plugin doesn't consider `'autowrite'` anymore.

And yes, `g:signify_realtime = 1` does save the buffer, as noted in the docs. Doing what what this plugin does without saving is not as easy as it seems considering all the supported VCS, but I'm working at it every now and then.
