### ISSUE TITLE
error in "q:" window

### ISSUE THREAD

**Issue by justinmk** [mhinz/vim-signify#231]
steps:

1. `q:`
2. open a tmux split to force a vim resize
3. close the tmux split

error occurs:

```
Error detected while processing function sy#util#refresh_windows:                                                                          
line    7:                                                                                                                                 
E11: Invalid in command-line window; <CR> executes, CTRL-C quits:   windo if exists('b:sy') | call sy#start() | endif
```

signify config:

```
  let g:signify_vcs_list = [ 'git' ]
  let g:signify_realtime = 1
```

**Comment by mhinz** [comment]
I can somewhat reliable detect the command-line window via `&buftype == 'nofile' && &filetype == 'vim'`? And then what?

I see just two ways currently:

1. Silently closing the command-line window and running `:SignifyRefresh`.
2. Use `silent!` and _not_ running `:SignifyRefresh`.

I think (2) sucks, but (1) would be even worse.

What do you think?

**Comment by justinmk** [comment]
What about `getcmdwintype()` ?

**Comment by justinmk** [comment]
Oh, the error is complaining about `:windo`. Can't that just be skipped if a cmdline window is visible?

**Comment by mhinz** [comment]
> Can't that just be skipped if a cmdline window is visible?

That's what I meant in (2). But then Sy won't refresh any window.

**Comment by mhinz** [comment]
So, (2). Silently ignoring `:window` and not doing anything?

**Comment by jamessan** [comment]
What about something like this?

```vim
au CmdwinEnter * let g:sy_cmdwin_active = 1
au CmdwinLeave * let g:sy_cmdwin_active = 0

" Function: #refresh_windows {{{1
function! sy#util#refresh_windows() abort
  if exists('*win_getid')
    let winid = win_getid()
  else
    let winnr = winnr()
  endif

  let cmdwin = get(g:, 'sy_cmdwin_active', 0)
  if cmdwin
    call feedkeys("\<C-c>\<Esc>", 'nixt')
  endif
  windo if exists('b:sy') | call sy#start() | endif

  if exists('winid')
    call win_gotoid(winid)
  else
    execute winnr .'wincmd w'
  endif
  if cmdwin
    normal! q:
  endif
endfunction
```

**Comment by jamessan** [comment]
Ok.  It was worth a shot.  Probably better to do the manual iteration anyway so the user's editing in the cmdwin isn't messed with.

**Comment by mhinz** [comment]
Then I could just use `silent! window ...`. :-P

In the best case, we somehow get the cmdwin to close, iterate through all other windows, reopen the cmdwin. That way the user might lose the current line of input in the cmdwin, but it's still the best solution I see.

So, somehow like jamessan's solution, only working. :-P I played around with some approaches, but I think it's the old problem of closing windows in an autocmd.. that always leads to weird behaviour.

**Comment by justinmk** [comment]
What's with with doing *nothing* ?

**Comment by tweekmonster** [comment]
> What's with with doing nothing ?

Did you mean what's wrong with doing nothing?  ¯\\\_(ツ)_/¯

> Then I could just use silent! windo .... :-P

This goofiness works:

```diff
diff --git a/autoload/sy/util.vim b/autoload/sy/util.vim
index 0501e8d..dd70a0c 100644
--- a/autoload/sy/util.vim
+++ b/autoload/sy/util.vim
@@ -22,8 +22,27 @@ function! sy#util#escape(path) abort
   return path
 endfunction
 
+function! s:cmdwin_refresh() abort
+  augroup sy_cmdwin
+    autocmd!
+    autocmd CursorMoved *
+          \ if empty(getcmdwintype()) |
+          \   call sy#util#refresh_windows() |
+          \   autocmd! sy_cmdwin |
+          \ endif
+  augroup END
+endfunction
+
 " Function: #refresh_windows {{{1
 function! sy#util#refresh_windows() abort
+  if !empty(getcmdwintype())
+    autocmd! CmdwinLeave <buffer> call s:cmdwin_refresh()
+    quit
+    return
+  endif
+
+  echomsg 'hooray!'
+
   if exists('*win_getid')
     let winid = win_getid()
   else
```

Tested it by doing:

```
q:
:call sy#util#refresh_windows()
```

**Comment by mhinz** [comment]
Okay, `:SignifyRefresh` will have no effect if executed from the cmdwin.

I added a NOTE to the docs.

@tweekmonster I decided not to rely on `getcmdwintype()`, because a lot of people that use Sy, because they use archaic VCS that often run on old computers etc. Unfortunately it's not uncommon that people still run Vim 7.3.

**Comment by mack-truck** [comment]
> I can somewhat reliable detect the command-line window via `&buftype == 'nofile' && &filetype == 'vim'`? And then what?
> 
> I see just two ways currently:
> 
> 1. Silently closing the command-line window and running `:SignifyRefresh`.
> 2. Using `silent!` and _not_ running `:SignifyRefresh`.
> 
> I think (2) sucks, but (1) would be even worse.
> 
> What do you think?

thank you, writing silent! worked for me
