### ISSUE TITLE
Show Diff Lines From A Commit/Id

### ISSUE THREAD

**Issue by umitkablan** [mhinz/vim-signify#232]
Thanks for the very useful/VCS agnostic plugin.

Do you have plans to show diff from a buffer-local-determined commit-ID? I am aware that plugin has many different VCS support but this commit ID might mean different concepts for each.

Best Regards,

**Comment by mhinz** [comment]
Sorry, we have no plans to add an extra feature like that for the very reason you mentioned.

Currently we have a single command for each VCS that is used to get the diff. You can change those commands, though. Have a look at `:h g:signify_vcs_cmds`. Maybe that's good enough for your use case already.

**Comment by coderonline** [comment]
I am currently using
`:let g:signify_vcs_cmds={'git': 'git diff --no-color --no-ext-diff -U0 HEAD~1: -- %f'}|:SignifyRefresh`
and am very happy with it. It is a great help when working in an unknown code repo to get an impression where people are currently working.
