### ISSUE TITLE
Plugin doesn't seem to work on Sparc

### ISSUE THREAD

**Issue by dagoss** [mhinz/vim-signify#233]
The plugin appears to do nothing. I'm not getting marks on any errors. My $VIMRC is being read an other plugins are loading--just not this one. I am using pathogen.

**Platform:** SunOS logo 5.10 Generic_150400-30 sun4v sparc sun4v
**Vim Version:** 7.2 (2008 Aug 9, compiled Feb 22 2009 06:30:54)

Here's my `:message` output:

```
could not source "$VIM/vimrc"
not found in 'runtimepath': "autoload/pathogen.vim"
Reading viminfo file "/hdrs/goss/.viminfo" info
Opening the X display failed
"content.md" 50L, 1166C
Reading viminfo file "/hdrs/goss/.viminfo" marks
not found in 'runtimepath': "ftplugin/modula2.vim ftplugin/modula2_*.vim ftplugin/modula2/*.vim"
not found in 'runtimepath': "indent/modula2.vim"
[sy] Register new file.
[sy:svn] get_diff_start()
[sy:svn] get_diff_svn()
[sy:svn] get_diff_end()
```

If the answer turns out to be "you're SOL because that is an uncommon platform and old version of Vim", I'm OK with that. Never hurts to ask though :)

**Comment by mhinz** [comment]
Can't blame lovers of legacy hardware. ;-)

Since you get the `[sy:svn]` messages, the plugins runs just fine, but it seems that it doesn't find a proper diff for the current file.

What's the output of `:SignifyDebug` and `:SignifyList`?

**Comment by dagoss** [comment]
The output of `:SignifyDebug` suggests the issue might actually be the version of SVN installed which (surprise!) is also old. The file I checked definitely has local changes (and `:!svn diff %` shows them correctly)

```
svn, version 1.8.9 (r1591380)
   compiled Jul  1 2014, 13:17:30 on sparc-sun-solaris2.10
```

Output of `SignifyDebug`:

```
svn diff --diff-cmd 'diff' -x -U0 -- '/hdrs/goss/WEB/dev/home.html'
========================================================================
Index: /hdrs/goss/dev/home.html
===================================================================
diff: illegal option -- L
usage: diff [-bitw] [-c | -e | -f | -h | -n | -u] file1 file2
       diff [-bitw] [-C number | -U number] file1 file2
       diff [-bitw] [-D string] file1 file2
       diff [-bitw] [-c | -e | -f | -h | -n | -u] [-l] [-r] [-s] [-S name] directory1 directory2
svn: E200012: 'diff' returned 2
```

**Comment by mhinz** [comment]
Okay, that explains why no signs are shown.

But.. huh? Where is the `L` in `illegal option -- L` coming from?

What happens if you execute this manually in a shell?

```
svn diff --diff-cmd 'diff' -x -U0 -- '/hdrs/goss/WEB/dev/home.html'
```

Same error?

**Comment by jamessan** [comment]
SVN 1.8.9 isn't that old.  The `diff: illegal option` and corresponding help look like they're from the `diff` command itself, not `svn diff` (since we're forcing the use of diff through `-diff-cmd diff`).

That doesn't explain the `illegal option -- L` bit though.

**Comment by jamessan** [comment]
Ah, subversion [adds] `-L` arguments to the diff command to label the before/after filenames.

@mhinz Is there a specific reason we're using `--diff-cmd diff` here instead of letting svn use its internal diff?

@dagoss If you put

```vim
let g:signify_vcs_cmds = {
    \ 'svn': 'svn diff -x -U0 -- %f'
    \ }
```

in your vimrc, does that fix the issue?

[adds]: https://svn.apache.org/viewvc/subversion/trunk/subversion/libsvn_subr/io.c?revision=1764436&view=markup#l3259

**Comment by jamessan** [comment]
@dagoss Alternatively, if `gnudiff` exists, you can `let g:signify_difftool = 'gnudiff'`.

**Comment by jamessan** [comment]
> Is there a specific reason we're using --diff-cmd diff here instead of letting svn use its internal diff?

I'm thinking a better default for svn might be `svn diff --internal-diff -x -U0 -- %f`.

**Comment by mhinz** [comment]
Oh, I didn't know about `--internal-diff`. I'd prefer this, yup.

**Comment by jamessan** [comment]
Hmm, except `--internal-diff` didn't support `-U` until 1.9.

**Comment by dagoss** [comment]
@jamessan Thanks for the suggestion. I tried putting that in my vimrc, but it seems my version of SVN (1.8.9) doesn't support `-U0`. It only allows `-u` (lower case) and defaults to 3.

From `svn help diff`

```
-x [--extensions] ARG    : Specify differencing options for external diff or
                             internal diff or blame. Default: '-u'. Options are
                             separated by spaces. Internal diff and blame take:
                               -u, --unified: Show 3 lines of unified context
                               -b, --ignore-space-change: Ignore changes in
                                 amount of white space
                               -w, --ignore-all-space: Ignore all white space
                               --ignore-eol-style: Ignore changes in EOL style
                               -p, --show-c-function: Show C function name
```

```
svn diff -x -U0 -- '/hdrs/goss/WEB/ppmd/web/home.html'
======================================================
svn: E200016: Error in options to internal diff
svn: E200016: invalid option character: U
```

**Comment by jamessan** [comment]
@dagoss Is there a way for you to get GNU's diff installed and use that? :)

**Comment by dagoss** [comment]
@jamessan Sorry, I forgot to answer that question. Unfortunately no, I can't. :(

**Comment by jamessan** [comment]
Then I guess the alternative is for Sy to not require `-U0`.

**Comment by mhinz** [comment]
Wait, do I misinterpret this?

```
-x [--extensions] ARG    : Specify differencing options for external diff or
                             internal diff or blame. Default: '-u'. Options are
                             separated by spaces. Internal diff and blame take:
                               -u, --unified: Show 3 lines of unified context
                               -b, --ignore-space-change: Ignore changes in
                                 amount of white space
                               -w, --ignore-all-space: Ignore all white space
                               --ignore-eol-style: Ignore changes in EOL style
                               -p, --show-c-function: Show C function name
```

Does this mean that before svn 1.9 one simply had to use `-u` instead of `-U`?

```viml
let g:signify_vcs_cmds = {
    \ 'svn': 'svn diff --internal-diff -x -u0 -- %f'
    \ }
```
?

**Comment by mhinz** [comment]
> Then I guess the alternative is for Sy to not require -U0.

But that makes the current algorithm so [straight-forward](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/sign.vim#L61).. :->

**Comment by jamessan** [comment]
> Does this mean that before svn 1.9 one simply had to use -u instead of -U?

`-u` doesn't take an argument.  It just sets the format of the diff to be unified context.

**Comment by mhinz** [comment]
@jamessan Oh. Right.

@dagoss 

I'd rather not change the main algorithm of this plugin for this, as you already mentioned in the first post, rather rare case, sorry. (Well, at least I won't look into it, because I think it will take more time to get right than I'm willed to invest at the moment. We're always open to PRs, of course!)

Your best bet is to find a way to compile a newer version of Subversion or find any diff tool that allows specifying 0 lines of unified context.

**Comment by dagoss** [comment]
@mhinz No worries. This isn't the first time our antiquated environment has left me on my own and I'm sure it won't be the last.
