### ISSUE TITLE
Prevent creation of new tab for SignifyFold

### ISSUE THREAD

**Issue by jgehrig** [mhinz/vim-signify#238]
Can we add a flag to prevent signify from creating a new tab on :SignifyFold?

Personally I would prefer it if signify would just create the folds within my current buffer. With the way I use buffers, it can be confusing/cumbersome when a new tab is created for each :SignifyFold.

I've added the following feature to my _vimrc (by modifying the vim-signify plugin). Could you officially support something like this?

.vimrc
`let g:signify_fold_usetabpage = 0`

vim-signify/autooad/sy/fold.vim
```
function! sy#fold#enable(do_tab) abort
  ...
  if a:do_tab
    if get(g:, 'signify_fold_usetabpage', 1)
      tabedit %
    endif
  endif
  ...
endfunction
```

Thanks for the great plugin!

**Comment by mhinz** [comment]
Hi,

See `:h :SignifyFold`. `:SignifyFold!` (mind the `!`) does already what you want!

> Thanks for the great plugin!

❤️
