### ISSUE TITLE
Jumping between hunks could wrap around end of file

### ISSUE THREAD

**Issue by hellbuster** [mhinz/vim-signify#239]
It would be nice if there is an option to allow the `signify-next-hunk` and `signify-prev-hunk` to wrap around the end and start of a file, respectively.

**Comment by mhinz** [comment]
I understand that some people prefer this behaviour and others another, but adding options for such small things has a cost. I don't want Sy to be one of those plugins that feature 1000 options.

I'd suggest using the `]C`/`[C` bindings instead.

If you really want wrapping, put this in your vimrc:

```vim
function! s:signify_hunk_next(count) abort
  let oldpos = getcurpos()
  call sy#jump#next_hunk(a:count)
  if getcurpos() == oldpos
    call sy#jump#prev_hunk(9999)
  endif
endfunction

function! s:signify_hunk_prev(count) abort
  let oldpos = getcurpos()
  call sy#jump#prev_hunk(a:count)
  if getcurpos() == oldpos
    call sy#jump#next_hunk(9999)
  endif
endfunction

nnoremap <silent> <expr> <plug>(sy-hunk-next) &diff
      \ ? ']c'
      \ : ":\<c-u>call <sid>signify_hunk_next(v:count1)\<cr>"
nnoremap <silent> <expr> <plug>(sy-hunk-prev) &diff
      \ ? '[c'
      \ : ":\<c-u>call <sid>signify_hunk_prev(v:count1)\<cr>"

nmap              ]c <plug>(sy-hunk-next)
nnoremap <silent> ]C :call sy#jump#next_hunk(9999)<cr>
nmap              [c <plug>(sy-hunk-prev)
nnoremap <silent> [C :call sy#jump#next_prev(9999)<cr>
```

This approach is similar to what we do [`plugin/signify.vim`](https://github.com/mhinz/vim-signify/blob/master/plugin/signify.vim#L78-L92), but makes `]c`/`[c` wrapping.

**Comment by mhinz** [comment]
Since I don't expect further comments, I'm closing this. Please reopen this issue if the above didn't help.
