### ISSUE TITLE
Some files produce errors on startup

### ISSUE THREAD

**Issue by Limeth** [mhinz/vim-signify#241]
I started getting these errors when opening, for example, [this file](https://gitlab.com/Limeth/dotfiles/blob/857a2a66725f60f8aeefd56a662d317bb6f7511f/link/.config/nvim/plug.vim).
Coincidentally, this is this the directory where all the vim scripts are, if that helps track down the bug.

```vim
Error detected while processing function signature#sign#Refresh[19]..signature#sign#Place[28]..<SNR>166_RefreshLine[15]..<SNR>166_EvaluateHL[8]..signature#sign#GetSignifyHLGroup:
line    7:
E119: Not enough arguments for function: sy#sign#get_current_signs
line    9:
E716: Key not present in Dictionary: internal, a:lnum)
E116: Invalid arguments for function has_key(b:sy.internal, a:lnum)
E15: Invalid expression: has_key(b:sy.internal, a:lnum)
line    7:
E119: Not enough arguments for function: sy#sign#get_current_signs
line    9:
E716: Key not present in Dictionary: internal, a:lnum)
E116: Invalid arguments for function has_key(b:sy.internal, a:lnum)
E15: Invalid expression: has_key(b:sy.internal, a:lnum)
Press ENTER or type command to continue
```

**Comment by mhinz** [comment]
```
Error detected while processing function signature#sign#Refresh[19]...
```

So, this is vim-signature calling a function from Sy without arguments. That function was changed a few months ago, when we switched to a completely asynchronous execution.

I'll create a PR for it.

Thanks for mentioning this!

**Comment by mhinz** [comment]
@Limeth https://github.com/kshenoy/vim-signature/pull/143

**Comment by Limeth** [comment]
Awesome, thanks for the quick response. 👍
