### ISSUE TITLE
Add --inter-hunk-context=0 to git diff

### ISSUE THREAD

**Issue by heftig** [mhinz/vim-signify#246]
If the user has configured `diff.interHunkContext`, sy must reset this by using `--inter-hunk-context=0` to get zero-context hunks again.

Unfortunately I think older git versions would complain about an unrecognized argument.

**Comment by mhinz** [comment]
> Unfortunately I think older git versions would complain about an unrecognized argument.

Unfortunately this is always a potential issue with this kind of plugin. There will always be a way to break a tool that relies on another tool by changing configs in unexpected ways.

And parsing program versions only leads to madness.

I prefer people to change the plugin as well if they use "unusual" (or new) tool configs.  The best suggestion I can make is putting this in your vimrc:

```vim
let g:signify_vcs_cmds = { 'git': 'git diff --inter-hunk-context=0 -U0 -- %f' }
```

HTH
