### ISSUE TITLE
Show only one column in gutter when no numbers present?

### ISSUE THREAD

**Issue by trusktr** [mhinz/vim-signify#252]
Sometimes there's no need for the second column if number aren't present. Is it possible to turn it on only if the number is present?

For example, if I have a `!` for modified for a single line, but no lines deleted anywhere in the file, then there's no need for the extra second column. Would be great to have the second column only when needed, for example for `_9` to show deletion count.

**Comment by mhinz** [comment]
Hi,

Vim calls the "gutter" sign column and unfortunately there's no way to change its width. It's hardcoded in Vim itself. It's always two characters.
