### ISSUE TITLE
]c and [c wait for input

### ISSUE THREAD

**Issue by dhduvall** [mhinz/vim-signify#254]
Maybe I have something configured incorrectly, but when I try to use `]c` and `[c` in normal mode to move between hunks, nothing happens. If I type a character (say, `j`), then the commandline shows
```
:<c-u>call sy#jump#next_hunk(v:count1)<cr>j
```
If I remove the `<cr>j` from the end and the `<c-u>` from the beginning, it finds the next hunk. If I do `:map`, I see
```
n  [c            <Plug>(signify-prev-hunk)
n  <Plug>(signify-prev-hunk) * &diff ? '[c' : ":<c-u>call sy#jump#prev_hunk(v:count1)<cr>"
```

This is on vim 8.0: 8.0.1401 on Debian unstable, 8.0.707 (with a lot of holes) on Debian stretch, and 8.0.642 on MacOS.

**Comment by mhinz** [comment]
My `:map` output looks like this:

```
n  <Plug>(signify-prev-hunk) * &diff ? '[c' : ":\<C-U>call sy#jump#prev_hunk(v:count1)\<CR>"
```

Note the backslashes in front of the `<c-u>` and `<cr>`.

I have no idea though why it would be any different for you, unless you set them yourself.

**Comment by dhduvall** [comment]
It appears the problem is because I'm setting `cpoptions` explicitly, rather than adding and removing stuff from it, and the value I have is missing `B`.
