### ISSUE TITLE
No diff tool found -> no support for svn, darcs, bzr, fossil.

### ISSUE THREAD

**Issue by gpakosz** [mhinz/vim-signify#256]
Hello,

When I launch Vim I'm being greeted by the "No diff tool found -> no support for svn, darcs, bzr, fossil." message despite having
```
let g:signify_vcs_list = [ 'git', 'hg' ]
```

Is it possible to echo an error message only if `svn`, `darcs`, `bzr`, `fossil` are being used?

**Comment by mhinz** [comment]
Thanks for letting me know! I can see how it must be annoying, so I made that message verbose-only for the time being.

I'll change it later to only get printed when any of these VCS is used in `g:signify_vcs_list`.

**Comment by gpakosz** [comment]
Thanks you!

**Comment by gpakosz** [comment]
BTW, I don't remember having ever seen this message on Windows.

But today I changed two things: I pulled by Vim configuration from GitHub to my Windows workstation and at the same time I re-installed Vim using Chocolatey's `vim-tux` package: https://chocolatey.org/packages/vim-tux

So it's possible the error didn't trigger with the official Vim. I don't know yet.
