### ISSUE TITLE
Errors when jumping to different location and repository using Tags

### ISSUE THREAD

**Issue by crapp** [mhinz/vim-signify#257]
Hi,

I am using the tags feature in my c++ projects. I am creating tags files for base libraries. These base libraries are managed with subversion. My project is managed using git (git svn). Whenever I use tselect to jump to a tag in one of the base libraries I get three messages from vim-signify

![error_tags_git_svn](https://user-images.githubusercontent.com/2805076/40228581-eec58964-5a91-11e8-8693-725da7f2817d.PNG)

Here is the error message:

> "e:\\viadat\\asbase\\3.2.0_viega\\src\\asbaslib\\get_seq.hpp" 54L, 1563C
Fehler beim Ausführen von "function sy#start[39]..sy#repo#detect[3]..sy#repo#get_diff_start":
Zeile   29:
E472: Befehl fehlgeschlagen
Fehler beim Ausführen von "function sy#start[39]..sy#repo#detect":
Zeile    3:
E170: Fehlendes :endfor
Fehler beim Ausführen von "function sy#start":
Zeile   39:
E171: Fehlendes :endif 

Maybe this has to do with my special setup. Two different vcs within one vim session. Just let me know if you need any further information.

**Comment by mhinz** [comment]
Hi,

- Does the plugin work for you at all if you use it with any toy (single VCS) subversion repo?
-  Does the file from `:tselect` gets opened besides the error message? The error suggests that the function [sy#repo#get_diff_start(), line 29](https://github.com/mhinz/vim-signify/blob/a1551dbae3b76035360b2ea2b38555194505d925/autoload/sy/repo.vim#L94) is failing. The code is run when you tag jump to a new file and Sy tries to detect its filetype. If you're in that file you tag jumped to, does this throw an error?

   ```vim
   :let [cwd, chdir] = sy#util#chdir()
   :execute chdir fnameescape(b:sy.info.dir)
   ```

**Comment by crapp** [comment]
Sorry my reply too so long but I was very busy at the office. 

> Does the plugin work for you at all if you use it with any toy (single VCS) subversion repo?

The plugin works great for me with git and svn repositories. I also realized this has nothing to do with git or subversion. When I use tselect inside my project and jumping to a file I get the same error messages.

> Does the file from :tselect gets opened besides the error message?

Yes the file opens but vim does not jump to the position in the file where the tag is

> The code is run when you tag jump to a new file and Sy tries to detect its filetype. If you're in that file you tag jumped to, does this throw an error?
`let [cwd, chdir] = sy#util#chdir()`

this command works just fine. See the output below
> ['E:\viadat\wms\viega\christian', 'cd']

`:execute chdir fnameescape(b:sy.info.dir)`

This command fails with E472. The output of `echo fnameescape(b:sy.info.dir)` is:
`e:\\viadat\wms\viega\christian\src\forkliftlib`

maybe there is a problem with the escaping of the backslash characters in the string? This command works:
`:execute chdir e:\\viadat\\wms\\viega\\christian\\src\\forkliftlib`

**Comment by mhinz** [comment]
I wonder why you even get `e:\\viadat\wms\viega\christian\src\forkliftlib` instead of `E:\viadat\wms\viega\christian\src\forkliftlib`.

The latter should work as well and it's what I get my Win 10 VM.

My Windows foo is weak.

**Comment by mhinz** [comment]
Oh, it's simply a network drive.

I also learned I could create custom network map to any directory. Now `z:` points to `c:\dir`. So, `:e z:\file` works, but `:e z:\\file` reproduces your problem.

That should make it easier to fix.

**Comment by mhinz** [comment]
Please update the plugin and see if the latest version is working for you.

**Comment by crapp** [comment]
@mhinz Works for me. Thanks a lot!!

**Comment by mhinz** [comment]
Awesome, thanks for bringing this up! ✨
