### ISSUE TITLE
Use patience/histogram diff if possible.

### ISSUE THREAD

**Issue by skywind3000** [mhinz/vim-signify#258]
I am not satisfied with the result of default `diff`. See the difference:

default diff:
![](https://github.com/chrisbra/vim-diff-enhanced/raw/master/default_diff.png)

histogram diff:
![](https://github.com/chrisbra/vim-diff-enhanced/raw/master/histogram_diff.png)

visit [vim-diff-enhanced](https://github.com/chrisbra/vim-diff-enhanced) for more information

signify could be better with the new diff algorithms

**Comment by jamessan** [comment]
Then change your config to use the a non-default diff configuration.  Signify lets you control how each vcs is run.

**Comment by skywind3000** [comment]
1. `g:signify_difftool` only accept an executable:
https://github.com/mhinz/vim-signify/blob/a1551dbae3b76035360b2ea2b38555194505d925/autoload/sy/repo.vim#L412-L414

but histogram diff requires a command like:
    git diff --diff-algorithm=histogram --no-index file1.txt file2.txt

and setting `g:signify_difftool` to a "git diff ..." will disable diff in svn/darcs.

2. some conversion are required:

https://github.com/chrisbra/vim-diff-enhanced/blob/3811527f584629d9f2e6947c337c122df741bdbe/autoload/EnhancedDiff.vim#L163-L170

it seems that `git diff` cannot be used directly as a replacement of `diff`, some conversion are required.

**Comment by mhinz** [comment]
See `:h g:signify_vcs_cmds`. Jamessan meant that you can control the exact command used with git, not changing the actual diff tool (which isn't used by git anyway).

Try this in your vimrc:

```vim
let g:signify_vcs_cmds = {
      \ 'git': 'git diff --diff-algorithm=histogram --no-color --no-ext-diff -U0 -- %f' }
```

**Comment by mhinz** [comment]
I verified that the above works, so I consider this solved.

Thanks for bringing this up!

**Comment by skywind3000** [comment]
What about svn ?? can I perform git diff --diff-algorithm=histogram in a svn repository ??

**Comment by mhinz** [comment]
Oh, I thought you only asked for git.

Adding the diff algorithm itself to this plugin is out-of-scope, but you can achieve what you want for svn anyway:

This plugin wraps around executables. As `:h g:signify_vcs_cmds` says, the default for svn is `'svn diff --diff-cmd %d -x -U0 -- %f'`. Here the `%d` will be replaced by `g:signify_difftool`.

To get a histogram diff with svn do this:

1. Put this shell script into `$PATH` and make it exectuable:

   ```sh
   # ~/bin/histogram
   git diff -U0 --histogram --no-index "$6" "$7"
   ```
   (You can use `svn diff --diff-cmd echo` in a svn repo with changes to see what arguments svn 
   provides to our wrapper script.)
1.
   Put this in your vimrc:

   ```vim
   let g:signify_difftool = 'histogram'
   ```

**Comment by cenkalti** [comment]
> See `:h g:signify_vcs_cmds`. Jamessan meant that you can control the exact command used with git, not changing the actual diff tool (which isn't used by git anyway).
> 
> Try this in your vimrc:
> 
> ```viml
> let g:signify_vcs_cmds = {
>       \ 'git': 'git diff --diff-algorithm=histogram --no-color --no-ext-diff -U0 -- %f' }
> ```

Using the latest git version (2.20.1). When `-U0` is applied, the diff algorithm does not change the output :(

I guess this is a problem with git, not vim-signify.

**Comment by mhinz** [comment]
@cenkalti 

With the diff mentioned in the first post, I can still reproduce it.

<details>
<summary>initial commit</summary>

```c
#include <stdio.h>

// Frobs foo heartily
int frobnitz(int foo)
{
  int i;
  for(i = 0; i < 10; i++)
  {
    printf("Your answer is: ");
    printf("%d\n", foo);
  }
}

int fact(int n)
{
  if(n > 1)
  {
    return fact(n-1) * n;
  }
  return 1;
}

int main(int argc, char **argv)
{
  frobnitz(fact(10));
}
```
</details>

<details>
<summary>changes</summary>

```c
#include <stdio.h>

int fib(int n)
{
  if(n > 2)
  {
    return fib(n-1) + fib(n-2);
  }
  return 1;
}

// Frobs foo heartily
int frobnitz(int foo)
{
  int i;
  for(i = 0; i < 10; i++)
  {
    printf("%d\n", foo);
  }
}

int main(int argc, char **argv)
{
  frobnitz(fib(10));
}
```
</details>

<details>
<summary>git diff -U0</summary>

```diff
diff --git i/test.c w/test.c
index 70a20a0..ed91079 100644
--- i/test.c
+++ w/test.c
@@ -3,2 +3 @@
-// Frobs foo heartily
-int frobnitz(int foo)
+int fib(int n)
@@ -6,2 +5 @@ int frobnitz(int foo)
-  int i;
-  for(i = 0; i < 10; i++)
+  if(n > 2)
@@ -9,2 +7 @@ int frobnitz(int foo)
-    printf("Your answer is: ");
-    printf("%d\n", foo);
+    return fib(n-1) + fib(n-2);
@@ -11,0 +9 @@ int frobnitz(int foo)
+  return 1;
@@ -14 +12,2 @@ int frobnitz(int foo)
-int fact(int n)
+// Frobs foo heartily
+int frobnitz(int foo)
@@ -16 +15,2 @@ int fact(int n)
-  if(n > 1)
+  int i;
+  for(i = 0; i < 10; i++)
@@ -18 +18 @@ int fact(int n)
-    return fact(n-1) * n;
+    printf("%d\n", foo);
@@ -20 +19,0 @@ int fact(int n)
-  return 1;
@@ -25 +24 @@ int main(int argc, char **argv)
-  frobnitz(fact(10));
+  frobnitz(fib(10));
```
</details>

<details>
<summary>git diff -U0 --histogram</summary>

```diff
diff --git i/test.c w/test.c
index 70a20a0..ed91079 100644
--- i/test.c
+++ w/test.c
@@ -2,0 +3,9 @@
+int fib(int n)
+{
+  if(n > 2)
+  {
+    return fib(n-1) + fib(n-2);
+  }
+  return 1;
+}
+
@@ -9 +17,0 @@ int frobnitz(int foo)
-    printf("Your answer is: ");
@@ -14,9 +21,0 @@ int frobnitz(int foo)
-int fact(int n)
-{
-  if(n > 1)
-  {
-    return fact(n-1) * n;
-  }
-  return 1;
-}
-
@@ -25 +24 @@ int main(int argc, char **argv)
-  frobnitz(fact(10));
+  frobnitz(fib(10));
```
</details>
<br>

This was also done with git 2.20.1. Maybe you dropped the `algorithm` in your gitconfig already and forgot about it?

**Comment by cenkalti** [comment]
It seems like working. I can reproduce it with the example you have provided. Probably there is something wrong with my setup. Thanks for the quick response 🚀
