### ISSUE TITLE
signify_realtime Not Working

### ISSUE THREAD

**Issue by slabounty** [mhinz/vim-signify#260]
I have the following in my `.vimrc` file (ok technically my `.vimrc.after` file for janus) ...

```
" Vim signify
let g:signify_realtime = 1
let g:signify_update_on_focusgained = 1
let g:signify_cursorhold_normal = 1
let g:signify_cursorhold_insert = 1
```

It still only seems to update when I write the file. This is mvim 8.1 on MacOS version 10.12.6. I'm guessing I'm just misunderstanding what I need to set or how it really works. Basically, I'm looking for realtime updates similar to what's available in `vim-gitgutter` (which has other issues for me).

Thanks for any help.

**Comment by mhinz** [comment]
Only `g:signify_realtime = 1` should be enough. It includes the other 3 options.

`:au signify` should look like this afterwards:

```
signify  BufEnter
    *         call sy#start()
signify  BufWritePost
    *         call sy#start()
signify  CmdWinEnter
    *         let g:signify_cmdwin_active = 1
signify  CmdWinLeave
    *         let g:signify_cmdwin_active = 0
signify  CursorHold
    *         call s:save()
signify  CursorHoldI
    *         call s:save()
signify  FocusGained
    *         SignifyRefresh
signify  QuickFixCmdPost
    *vimgrep* let g:signify_locked = 0
signify  QuickFixCmdPre
    *vimgrep* let g:signify_locked = 1
signify  WinEnter
    *         call sy#start()
```

Obviously I'm not using vim-gitgutter, so what _exactly_ is not working?

**Comment by slabounty** [comment]
Sorry about the lack of clarity. What I'm looking for is a semi-immediate update which I think is what the `realtime` flag is doing. I also don't see an update on enter/leave the window or on cursor hold. I don't see the same thing as you for the `au signify`, here's what I have ...

```
:au signify
--- Auto-Commands ---
signify  BufRead
    *         call sy#start()
signify  BufWritePost
    *         call sy#start()
signify  CmdwinEnter
    *         let g:signify_cmdwin_active = 1
signify  CmdwinLeave
    *         let g:signify_cmdwin_active = 0
signify  QuickFixCmdPost
    *vimgrep* let g:signify_locked = 0
signify  QuickFixCmdPre
    *vimgrep* let g:signify_locked = 1 
```
Also, I see the same thing if I just set the value inside of mvim with just a 

```
:let g:signify_realtime = 1
```

so it seems that for some reason it's not seeing or accepting the value maybe?

Thanks for whatever help you can provide.

**Comment by mhinz** [comment]
Options are only read at start. Using `:let g:signify_realtime = 1`, won't change any autocmds. But when you put `let g:signify_realtime = 1` in your vimrc instead and restart Vim, the output of `:au signify` should look like in my case.

**Comment by slabounty** [comment]
OK ... for anyone using Janus, you'll need to add these in your `~/.vimrc.before` and not your `~/.vimrc.after` file. 

Thanks for the help!

**Comment by mhinz** [comment]
Hah, mystery solved! ✨
