### ISSUE TITLE
On the road to 2.0

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-signify#261]
The 2.0 release of this plugin won't be about new features, but about..

- ~~**Cleaning up the code**: Support for Vim versions older than 8.0 will be removed. That will make it easier to reason about other features.~~
- **Removing options**: Options are easy to add, but hard to maintain. Most importantly, I want to reduce the sheer number of options, to make it easier for the user to just get work done. ([This is a great summary about the cost of options.](http://neugierig.org/software/blog/2018/07/options.html))

---

To-do list:

- ~~Remove support for Vim versions older than 8.0. People who get forced by their employers to use obsolete versions, will be able to check out the lightweight tag `legacy`, which will point to the last commit still supporting old Vim versions.~~ The code for supporting legacy versions is quite short, so keeping it is a no-brainer.

- ~~I'll improve the documentation around all options that set autocmds and stress that users should usually only care about whether to use `g:signify_realtime = 1` or not. (And that "realtime" has nothing to do with the usual definition of realtime..) All the other options are only for the most demanding users.~~ `g:signify_realtime` was removed.

- ~~Remove `g:signify_vcs_list`. The behaviour of how external VCS tools get registered changed a few times over the lifetime of this plugin. Back when Vim didn't have support for asynchronous execution, `g:signify_vcs_list` was the most important option by far. If it wasn't set to only the VCS tools in use, Sy would shell out for each tool it supported and Vim would block in the meantime. Not cool. Nowadays all the probing happens only once, in the background, and parallel. The user won't notice any blocking.~~ Done.

**Comment by jamessan** [comment]
> The behaviour of `g:signify_realtime = 1` will become the default.

If this means Sy will automatically save my buffer by default, I think that's a non-starter.

Aside from that, I've never really understood the point of `g:signify_realtime = 1`.  The only benefit I see to this over `g:signify_realtime = 0` is when there's an expectation of something other than Vim modifying the file.  Otherwise, the non-realtime setup covers the common use-cases of determining what's modified when the buffer is first loaded and when it is written to disk.

On the other hand, enabling `g:signify_update_on_focusgained` makes sense since then there's at least an indication that something _may_ have happened external to Vim, and it doesn't save the buffer.

**Comment by mhinz** [comment]
What about making the behaviour of `g:signify_realtime = 1` the default, but having a new option that disables all autocmds that also save the buffer? `g:signify_save_buffer = 0`? That means not setting the autocmds for `CursorHold`/`CursorHoldI` and not updating the buffer on `BufEnter`.

Good compromise?

**Comment by vdrandom** [comment]
What will be the implications of `g:signify_realtime = 1` default? I don't mind signs being updated on the fly, but doesn't it have to, like, write a swap-file on the filesystem to run diff? Same goes for the `g:signify_vcs_list`, although from what I can tell the impact on the performance is not noticeable even if I close vim every time I edit a file.

I don't have much experience with viml, so I don't think that it would be easy for me to find that out myself.

**Comment by mhinz** [comment]
@vdrandom 

> Same goes for the g:signify_vcs_list, although from what I can tell the impact on the performance is not noticeable even if I close vim every time I edit a file.

Yup, with a modern Vim there's not much use for this option anymore. Hence it should be removed.

> What will be the implications of g:signify_realtime = 1 default? I don't mind signs being updated on the fly, but doesn't it have to, like, write a swap-file on the filesystem to run diff?

`g:signify_realtime = 1` makes run Sy on more events whereas a few of them do save the current buffer. (The current default of `g:signify_realtime = 0` _never_ saves the buffer.)

BTW, `:h g:signify_realtime` lists the exact events.

I think it's less a question of performance and more about being in control when a buffer should be written to disk. So I understand that we need at least one option to configure that behaviour and my suggestion is `g:signify_save_buffer`. We just have to decide whether it should be 0 or 1 by default. ;-)

**Comment by jamessan** [comment]
I think `g:signify_save_buffer = 0` is the right default.  It's the smooth update from the existing Sy defaults.

FWIW, the reasoning I'm strongly against automated saving is that it takes control out of the user's hands and it potentially kicks off various other plugins' features that trigger on save.

**Comment by jamessan** [comment]
I do empathize with the desire to remove options, but attacking the "realtime" vs. "non-realtime" aspect of the plugin doesn't really do much in that regard.  Making the changes to have realtime be default but let users decide if they want Sy to save is a pretty minimal code change (docs are more):

```diff
diff --git a/plugin/signify.vim b/plugin/signify.vim
index e08316a..2aa60f1 100644
--- a/plugin/signify.vim
+++ b/plugin/signify.vim
@@ -23,36 +23,15 @@ augroup signify
 
   autocmd BufWritePost * call sy#start()
 
-  if get(g:, 'signify_realtime') && has('patch-7.4.1967')
-    autocmd WinEnter * call sy#start()
-    if get(g:, 'signify_update_on_bufenter')
-      autocmd BufEnter * nested call s:save()
-    else
-      autocmd BufEnter * call sy#start()
-    endif
-    if get(g:, 'signify_cursorhold_normal', 1)
-      autocmd CursorHold * nested call s:save()
-    endif
-    if get(g:, 'signify_cursorhold_insert', 1)
-      autocmd CursorHoldI * nested call s:save()
-    endif
-    if get(g:, 'signify_update_on_focusgained', 1)
-      autocmd FocusGained * SignifyRefresh
-    endif
+  autocmd WinEnter * call sy#start()
+
+  if get(g:, 'signify_save_buffer')
+    autocmd BufEnter * nested call s:save()
+    autocmd CursorHold * nested call s:save()
+    autocmd CursorHoldI * nested call s:save()
   else
-    autocmd BufRead * call sy#start()
-    if get(g:, 'signify_update_on_bufenter')
-      autocmd BufEnter * nested call s:save()
-    endif
-    if get(g:, 'signify_cursorhold_normal')
-      autocmd CursorHold * nested call s:save()
-    endif
-    if get(g:, 'signify_cursorhold_insert')
-      autocmd CursorHoldI * nested call s:save()
-    endif
-    if get(g:, 'signify_update_on_focusgained')
-      autocmd FocusGained * SignifyRefresh
-    endif
+    autocmd BufEnter * call sy#start()
+    autocmd FocusGained * SignifyRefresh
   endif
 
   if has('gui_running') && has('win32') && argc()
```

It certainly makes that part of the code _easier_ to read, but I don't think it reduces overall complexity at all.  The main benefit is reducing the scope of what users need to make choices about (which your original post alluded to).

I don't have a strong opinion between applying the above diff (along with docs updates) or simply changing the existing documentation.

One thing I did notice is that the two `signify_update_on_` variables differ with regard to whether they save the buffer.  That could be a point of confusion since people may intuit the `update` to mean `save`.

**Comment by mhinz** [comment]
> One thing I did notice is that the two signify_update_on_ variables differ with regard to whether they save the buffer. That could be a point of confusion since people may intuit the update to mean save.

Yup, in the beginning it meant "update signs on...", but some options were made to save later on. Confusing, indeed. Another reason to remove these.

I'll put up a PR tomorrow and see where this is going.

**Comment by puremourning** [comment]
FWIW my 2p: no plug-in should ever unsolicitedly save the buffer, for any reason. Ideally it should never do it even in response to a user command, but certainly not as an autocommand.

**Comment by mhinz** [comment]
Well, some functionality requires saving, but it won't happen by default.

**Comment by glhrmv** [comment]
`vim-gitgutter` can update its sign column in real time without saving the buffer. I don't know how it works implementation-wise but is that not possible for this project? Setting `realtime` on by default is a good move only if the buffer isn't written by the plugin. 
In any case, I'm looking forward to 2.0.

**Comment by otherjoel** [comment]
> The problem is that this approach is not feasible for all the tools that we support and I'm reluctant to implement this only for some of them.

I understand and admire this impulse, but I think people would understand if you did add realtime-without-autosave for the tools that would support it. If I use one of the non-supported tools, Signify will continue to work as it always has; if I use one of the supported ones, I get additional functionality that brings me up to par with the baseline for most modern editors.

**Comment by kevincox** [comment]
> The problem is that this approach is not feasible for all the tools that we support

Why isn't this feasible for all of the supported tools? The only functionality required from the VCS would be to dump the "base" version of the file. I have yet to see a VCS system which can't do this.

I also think that saving the user's file for them is unacceptable and while realtime would be cool it can only happen if there is no saving required.

**Comment by mhinz** [comment]
We now have all features together to begin the big refactoring. 🎉 Thanks again, @kevincox.

Versioning doesn't work for Vim plugins. If the `master` branch, which you should use by default, should ever break for you, checkout the `stable` branch. That's a moving lightweight tag which will point to whatever version I consider to be stable at any given time.

As of today, the master branch enabled saveless updates by default. It seems to work fine on Unix-likes and Windows with `set shell=cmd`. Please report any issues with it immediately. :)

I'll use this issue for status updates.

**Comment by mhinz** [comment]
Okay, everything's done now.

Signs update without saving the buffer and Sy runs on all the events that used to be enabled with `g:signify_realtime = 1` by default now. The option itself, was removed. See `:h signify-autocmds`.

Also removed:

- `g:signify_vcs_list`
- `g:signify_update_on_bufenter`
- `g:signify_update_on_focusgained`
- `g:signify_cursorhold_normal`
- `g:signify_cursorhold_insert`

And if you don't know about these commands yet, check out `:h :SignifyHunkDiff` and `:h :SignifyHunkUndo`!
