### ISSUE TITLE
[C ]C

### ISSUE THREAD

**Issue by squm** [mhinz/vim-signify#264]
https://github.com/mhinz/vim-signify/blob/a9fc705b9bdffaac46f13e47d6565c904102dedc/plugin/signify.vim#L90

forgot to check `[C` and `]C`

**Comment by mhinz** [comment]
Right. I'll change it to `hasmapto()` for `]c`/`[c` _and_ `]C`/`[C`. (But probably not before Friday, because I'm away until then.)
