### ISSUE TITLE
Fold diffs by default

### ISSUE THREAD

**Issue by spar01** [mhinz/vim-signify#268]
Currently on invoking :SignigyDiff, the fold on the edited version of the file are opened whereas the folds on the original version are closed. This seems a little inconsistent to me. Do you think it would make sense to fold both? That would make it easier to follow the diffs as well. Users can then use 'za' to toggle the folds if needed.

**Comment by spar01** [comment]
I tried this by removing the foldopen command in the diffmode function. Seems to work well.

I am not sure what the intent of the folding behaviour was originally, but if not by default then maybe could you consider adding this as a user configurable option?

Let me know if you think this is something you want to add and I can create a PR :grinning:

**Comment by mhinz** [comment]
Hmm, you're right. It never bothered me, but I agree that it's probably not expected.

Please send a PR!

**Comment by spar01** [comment]
Created PR #269
