### ISSUE TITLE
Signify on Angular components

### ISSUE THREAD

**Issue by stoicAlchemist** [mhinz/vim-signify#273]
Hi, I'm loving the plugin but I've started working with a tutorial for Angular 6 and keep having things not identified like components:

![default](https://user-images.githubusercontent.com/1622554/47106001-1eeb2400-d20b-11e8-9003-0ad79e7b3fa1.png)

it complains on <app-root> not being recognized, is it the plugin? or how does this work to track down the issue?

**Comment by jamessan** [comment]
> I've started working with a tutorial for Angular 6 and keep having things not identified like components:

All Signify does is add signs where your vcs reports there are uncommitted differences.  In that context, `having things not identified like components` doesn't mean anything to me.  The picture doesn't help.

What exactly are you expecting to happen?

> how does this work to track down the issue?

`:SignifyDebug` is the typical way to debug what's happening.

**Comment by stoicAlchemist** [comment]
Maybe it's the wrong plugin doing this, sorry for the noise, the thing is that it's showing the error `<app-root> is not recognized!` but again, this might be another plugin, I'll close it and investigate further, will re-open if I find out anything. (thought it was signify because of the gutter sign >>
