### ISSUE TITLE
DiffChange vs DiffText - colour scheme settings

### ISSUE THREAD

**Issue by orao** [mhinz/vim-signify#276]
I have noticed that the code of [vim-signify](mhinz/vim-signify) doesn't reference the `DiffText` property much like [vim-gitgutter](http://github.com/airblade/vim-gitgutter). See discussion in [vim-gitgutter issue #560](https://github.com/airblade/vim-gitgutter/issues/560). I think that whatever resolution is there would likely be beneficial to this plugin as well.

**Comment by mhinz** [comment]
This heavily depends on the given colorscheme. I don't think it should be changed by default, but, just in case in wasn't obvious from `:h signify-colors`, I added a small example for this exact use case.

Thanks for bringing this up! ✨
