### ISSUE TITLE
Gutter only updating on a write

### ISSUE THREAD

**Issue by sethen** [mhinz/vim-signify#277]
Looks like I am having trouble with the real time option.  My `init.vim` is super minimal and there's nothing crazy going on:

```
call plug#begin('~/.local/share/nvim/plugged')
    Plug 'mhinz/vim-signify'
    Plug 'scrooloose/nerdtree'
call plug#end()

let g:signify_realtime = 1

syntax on                   " enables syntax highlighting
set cursorcolumn            " set vertical line on where cursor currently is
set cursorline              " set horizontal line on where cursor currently is
set number                  " set line number
set shortmess=I             " get rid of message prompt on startup
set termguicolors           " use 24-bit color

highlight CursorLine cterm=bold ctermbg=238
highlight CursorColumn cterm=bold ctermbg=238
```
I am using Neovim on Ubuntu 18.04.

Signify works when I write a file, but when I insert nothing happens.  Shouldn't the `realtime` option update the gutter while inserting?

**Comment by mhinz** [comment]
See `:h g:signify_realtime`. The plugin updates the sign column (not "gutter") on several events. The ones you're thinking of are `:h CursorHold` and `:h CursorHoldI`. These rely on `:h 'updatetime'`.

So, by default, the signs should get updated after 4s of not moving the cursor in insert or normal mode. If that's too long for your liking, set `'updatetime'` to a lower value.

HTH ✨

**Comment by sethen** [comment]
@mhinz Ah I see.  Is there anyway to update the gutter more aggressively?

**Comment by sethen** [comment]
@mhinz Ah okay.  Even with that option on in the `.vimrc` the git gutter still doesn't update, only works on a write.  If I am reading you correctly (as I am new to Vim), the gutter is supposed to update every 4 seconds in insert mode?

**Comment by mhinz** [comment]
Okay, just so we're on the same page. I assume you have this at the end of your vimrc:

```vim
set updatetime=500
let g:signify_realtime = 1
```

If you open a VCS-controlled file, and the cursor is on a line without changes, switch to insert mode with `i` and insert a single character. Now, after ~500ms the sign column should update for the current line to indicate the change.

Is this working?

**Comment by sprt** [comment]
Same issue for me, gutter not updating until I press `:w`, even with this at the very end of vimrc:

    set updatetime=1
    let g:signify_realtime = 1

`:au signify CursorHoldI` returns this:

    --- Auto-Commands ---
    signify  CursorHoldI
        *         call sy#start()

**Comment by mhinz** [comment]
@sprt 

If you're using master, then `g:signify_realtime` doesn't exist anymore. Everything is enabled by default now, because sign updates don't require saving the buffer anymore.

See `:h signify-autocmds`.

Your `:au signify CursorHoldI` shows the the handler is set and the plugin is working, so maybe you just need to adjust `'updatetime'`? It's set to 4 seconds by default. Try `:set updatetime=100`.
