### ISSUE TITLE
no such file or directory: "cmd.exe"

### ISSUE THREAD

**Issue by wsdjeg** [mhinz/vim-signify#279]
When using this plugin in win7, I get following errors, It is hard to reproduce.

the errors is:

```


Error detected while processing function sy#start[42]..sy#repo#detect[3]..sy#repo#get_diff_start:
line   13:
E903: Process failed to start: no such file or directory: "cmd.exe"
```

**Comment by mhinz** [comment]
There is no cmd.exe on Windows 7?

**Comment by wsdjeg** [comment]
1.  there is `cmd.exe` in win7
2. I do not change &shell, it is cmd.exe
3. I am uing neovim

```
NVIM v0.3.1
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
[sy] Register new file: C:\Users\Administrator\.SpaceVim.d\init.toml
[sy:git] get_diff_start()
[sy:git] CMD: 'git diff --no-color --no-ext-diff -U0 -- "init.toml"' | CWD: C:\Users\Administrator\.SpaceVim.d
Error detected while processing function sy#start[42]..sy#repo#detect[3]..sy#repo#get_diff_start:
line   13:
E903: Process failed to start: no such file or directory: "cmd.exe"
```

`C:\Users\Administrator\.SpaceVim.d` is a link to `C:\Users\Administrator\DotFiles\SpaceVim.d`

here is how I create this link:

```
mklink C:\Users\Administrator\.SpaceVim.d C:\Users\Administrator\DotFiles\SpaceVim.d
```

**Comment by mhinz** [comment]
Unfortunately I have no Windows 7 to test that. Any help is appreciated.

**Comment by mhinz** [comment]
Ok, we just bail out now in such cases. Thanks for reporting this! ✨

**Comment by wsdjeg** [comment]
Thanks for your work.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [mhinz/vim-signify] no such file or directory: "cmd.exe" (#279)
发件人：Marco Hinz
收件人：mhinz/vim-signify
抄送：Wang Shidong ,Author


Ok, we just bail out now in such cases. Thanks for reporting this! ✨

**Comment by wsdjeg** [comment]
@mhinz This error has not been fixed, I still get:

```
Error detected while processing function sy#start[42]..sy#repo#detect[3]..sy#repo#get_diff_start:
line   13:
E903: Process failed to start: no such file or directory: "cmd.exe"

```
I just read line 13 in `sy#repo#get_diff_start`, it is:

```viml
    let b:sy_job_id_{a:vcs} = jobstart(cmd, extend(options, {
          \ 'cwd':       b:sy.info.dir,
          \ 'on_stdout': function('s:callback_nvim_stdout'),
          \ 'on_exit':   function('s:callback_nvim_exit'),
          \ }))
```

and I also run `:echo b:sy.info.dir`, it show me `C:\Users\Administrator\.SpaceVim.d`, which is a link maked by mklink.

**Comment by wsdjeg** [comment]
sorry, It seem my plugin is not updated succescfully. It works well now.
