### ISSUE TITLE
signcolumn is ugly when solarized8 colorscheme is used

### ISSUE THREAD

**Issue by ppnman** [mhinz/vim-signify#286]
Hi, @mhinz , I am using [solarized8](https://github.com/lifepillar/vim-solarized8) color scheme.
But the signcolumn is inharmonious, like following:
![screenshot from 2019-02-20 00-10-38](https://user-images.githubusercontent.com/39628662/53079593-c10c7700-3531-11e9-8288-80437faa4ae4.png)

The method referred to by https://github.com/mhinz/vim-signify/issues/128#issuecomment-137800860 does not work for me.
Can you help me ? I will be very grateful !

**Comment by mhinz** [comment]
These colors come from the colorscheme. See `:h signify-colors`

You didn't say exactly what you want to see, but you either want change the background color of `SignColumn` or of `SignifySignAdd` etc.

- What's the output of `:echo g:colors_name`?
- What's the output of `:hi Number`?

**Comment by ppnman** [comment]
@mhinz  I am very grateful for your answer.
I want the signcolumn has only one color, not this like
![image](https://user-images.githubusercontent.com/39628662/53089008-5154b700-3546-11e9-947d-d1bbaac36486.png)
There are two colors of background obviously.
Output of `:echo g:colors_name` is `solarized8`.
Output of `:hi Number` is `Number         xxx links to Constant`
I am a green hand to vim, really not know how to modify `SignColum` or `SignifySignAdd`.

**Comment by mhinz** [comment]
Then I need the output of `:hi Constant` as well.

Afterwards we can create an autocmd, that changes the background color of `SignColumn` every time you do `:colorscheme solarized8`.

**Comment by ppnman** [comment]
Output of `:hi Constant` is `Constant       xxx term=underline ctermfg=37 guifg=#2aa198`.

**Comment by mhinz** [comment]
Try putting this in your vimrc _before_ `colorscheme solarized8`:

```vim
autocmd ColorScheme solarized8 highlight SignColumn guibg=#073642
```

**Comment by ppnman** [comment]
Wow, It solve my problem perfectly!
I don't know how to express my thanks to you.
Thanks for your patience to me such a fool.

**Comment by mhinz** [comment]
You're welcome!
