### ISSUE TITLE
It automatic saving my buffer

### ISSUE THREAD

**Issue by chemzqm** [mhinz/vim-signify#287]
Is that a desired behavior?

I only have `  let g:signify_realtime = 1` for configuration.

**Comment by mhinz** [comment]
Currently, yes, as stated in `:h g:signify_realtime`.

**Comment by chemzqm** [comment]
But the documentation doesn't mention that it will save save buffer on those autocmds.

**Comment by mhinz** [comment]
https://github.com/mhinz/vim-signify/blob/master/doc/signify.txt#L207
https://github.com/mhinz/vim-signify/blob/master/doc/signify.txt#L210
