### ISSUE TITLE
Errors saving files, SY failes and gutter signs not update

### ISSUE THREAD

**Issue by alzedd** [mhinz/vim-signify#293]
Hi guys, when I save a file in a git repo the first time everything works fine, the second time I got this error:

`Errore/i eseguendo function <SNR>125_callback_nvim_exit[1]..<SNR>125_job_exit[12]..sy#repo#get_diff_git[3]..<SNR>125_g
et_diff_end[6]..sy#set_signs[20]..sy#sign#process_diff[5]..sy#sign#get_current_signs:
riga   10:
E684: indice lista fuori intervallo: 1
`

**(translating from italian)**
`error executing function <SNR>.................
line 10:
index list out of bound: 1`

I'm using Neovim in a shell, no problem found with macvim
my vimrc https://github.com/alzedd/dotfiles/tree/feat/vim-config

**Comment by mhinz** [comment]
Can you save once and then paste the output of `:sign place`?

The problem is that `tokens` is empty in [this case](https://github.com/mhinz/vim-signify/blob/bdbda32568ee97472b320325c29578badb5ae1d9/autoload/sy/sign.vim#L32-L33). Therefore the line below fails.

**Comment by alzedd** [comment]
**first save**
Opened a file without modifications since last commit, added an empty line (15) and an another line (16) 
`Segni per main.go:
    riga=15 id=256, nome=SignifyAdd
    riga=16 id=257, nome=SignifyAdd
`
after that, i got the same error

**Comment by mhinz** [comment]
That's kind of what I expected: an i18n issue: https://github.com/neovim/neovim/blob/76204da1f8ed63f7b0ef15ad7c71ce6e2e58d8fb/src/nvim/po/it.po#L249-L250

Using `:lang message C` makes it work, right? Because it would be better to temporarily set that before `sign place` instead of changing the regexp to take all these kind of issues into account.

**Comment by alzedd** [comment]
using ```:language C``` fixes everything, I've added it in my vimrc, but should I notify the translations maintainers of this bug?

**Comment by jamessan** [comment]
> it would be better to temporarily set that before `sign place` instead of changing the regexp to take all these kind of issues into account

Won't it be nice when we can use the sign APIs instead? :)

**Comment by mhinz** [comment]
@alzedd I just noticed we already set the language for the exact same command in another place.. d'oh! You can contact the author if you want, but notice that Vim's po files are more up-to-date at the moment: https://github.com/vim/vim/blob/0e97b9487571cf725a9cb28fe4dcefc800415f69/src/po/it.po#L5152-L5153

@jamessan  Yeah, someone should port these patches to Nvim. :]
