### ISSUE TITLE
Seeing -1 in the gutter

### ISSUE THREAD

**Issue by jrock2004** [mhinz/vim-signify#296]
Not sure why, but I am seeing a `-1` in the left gutter. Not sure if something is conflicting or not

```
Plug 'mhinz/vim-signify'
let g:signify_vcs_list = [ 'git' ]
let g:signify_sign_add				 = '|'
let g:signify_sign_delete			 = '-'
let g:signify_sign_delete_first_line = '_'
let g:signify_sign_change = '|'
```

![image](https://user-images.githubusercontent.com/655716/57498263-31ad6f00-72a9-11e9-9a9d-d8b8cda8c3a1.png)

Thoughts?

**Comment by mhinz** [comment]
It's the number of deleted lines. :) See `:h g:signify_sign_show_count`.
