### ISSUE TITLE
Support files tracked by yadm

### ISSUE THREAD

**Issue by davidtwco** [mhinz/vim-signify#297]
[yadm](https://yadm.io/) is a dotfiles manager that wraps git, you invoke it with `yadm` and use the regular git subcommands and it operates on a repo in your home directory.

When making changes to files tracked by yadm, such as `.vimrc`, vim-signify doesn't show the sign column (because it only looks for changes to files tracked by `git`, not `yadm`). 

It would be good if vim-signify could be configured to checked for file changes from `yadm` and `git`.

**Comment by mhinz** [comment]
How would this plugin know that a file is managed by yadm?

See if you can get it to work by using `:h g:signify_vcs_cmds`.

**Comment by davidtwco** [comment]
@mhinz If I set the following, then it just works, however, vim-signify then wouldn't work with regular git repositories:

```vim
let g:signify_vcs_cmds = {
\ 'git': 'yadm diff --no-color --no-ext-diff -U0 -- %f',
\ }
```

**Comment by mhinz** [comment]
Could you see if the `yadm` branch is working as expected? (Are the signs showing up? Is `:SignifyDiff` working?)

**Comment by davidtwco** [comment]
@mhinz That works great. Thanks.

**Comment by mhinz** [comment]
Merged. Thanks! ✨
