### ISSUE TITLE
Stop working on Windows

### ISSUE THREAD

**Issue by zdm** [mhinz/vim-signify#298]
Hi.
vim 8.1.1413 on linux and windows.
The vim configs are the same, and didn't changed.
On linux everything is ok, on windows - don't show anything.

**Comment by mhinz** [comment]
- What is your config?
- Which VCS? Does it work in cmd.exe or powershell?
- When did it stop working? When you updated Vim or the plugin?

**Comment by zdm** [comment]
Hi.

1. Config is simple:
let g:signify_vcs_list = [ 'hg', 'git' ]
let g:signify_realtime = 1

2. VCS is hg. Everything works, I use it constantly.

3. Hard to say. Came vim, vim config and hg version works under linux
without problems.

**Comment by mhinz** [comment]
Okay, thanks! I'll look into it, but it might take some time since I neither use Windows nor Mercurial. :)

**Comment by zdm** [comment]
Thank you.
I can help you with testing.

**Comment by mhinz** [comment]
1. What's the output of `:SignifyDebug`?
1. Do `:verb w` followed by `:messages`. What's the output? It should be something like this (just for hg):

    ```
    [sy:git] Updating signs.
    [sy:git] get_diff_start()
    [sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''vimrc''']

    [sy:git] CMD DIR:  /Users/mhi/.vim
    [sy:git] ORIG DIR: /Users/mhi
    ```

**Comment by zdm** [comment]
:SignifyDebug
```
diff -r 282e13c27cbb TODO.txt
--- a/TODO.txt
+++ b/TODO.txt
@@ -8,0 +9,3 @@
+
+
+

git diff --no-color --no-ext-diff -U0 -- "TODO.txt"
===================================================
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>


Press ENTER or type command to continue
```

:messages
```
Writing undo file: C:/Users/zdm/.vim/undo\d%%work%fbadbot%TODO.txt
[sy] Detection is already in progress.
Press ENTER or type command to continue
```

**Comment by mhinz** [comment]
Where is the `diff -r` coming from? That's not a default VCS.
- And it seems that hg is never even tried? Does `hg` work in whatever `:echo &shell` reports? (So either cmd.exe or powershell)

**Comment by zdm** [comment]
1. I have msys2 installed, diff is from there;
2. shell is cmd.exe;

I have hg in the path, but this is not hg.exe but hg.cmd. Maybe this is the reason, why signify don't fimd hg? But previously it worked.

**Comment by mhinz** [comment]
Oh, wait.. there first lines of the `:SignifyDebug` output were missing, right? I assume it's hg that returned the valid diff output. Is that correct?

**Comment by mhinz** [comment]
What does `:SignifyList` say?

**Comment by zdm** [comment]
Here is the full output again
```
hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"
========================================================================================
diff -r 282e13c27cbb TODO.txt
--- a/TODO.txt
+++ b/TODO.txt
@@ -8,0 +9,4 @@
+
+
+
+:

git diff --no-color --no-ext-diff -U0 -- "TODO.txt"
===================================================
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>


Press ENTER or type command to continue
```

**Comment by zdm** [comment]
:SignifyList
```
d:\work\fbadbot\TODO.txt
========================
    active  =  1
    buffer  =  1
       vcs  =  []
     stats  =  -1 added, -1 changed, -1 removed
    signid  =  256
     hunks  =  []
```

**Comment by mhinz** [comment]
Hmm. Okay.. so the VCS detection (which relies on async execution unlike `:SignifyDebug`) fails for some reason.

Thanks, now I know where to look!

**Comment by zdm** [comment]
ok, i am here
tell me if you will need something

**Comment by mhinz** [comment]
Is git working or is no VCS at all working on Windows?

**Comment by zdm** [comment]
git also not working.

**Comment by mhinz** [comment]
Hmm, I just installed TortoiseHg and Vim 8.1.1413 and it works for me.

So, maybe it's related to the msys2 environment somehow.. hm.

**Comment by zdm** [comment]
maybe the problem with the vim version?
what version do you have?

**Comment by mhinz** [comment]
> Vim 8.1.1413

Installed from: https://github.com/vim/vim-win32-installer/releases/download/v8.1.1413/gvim_8.1.1413_x64_signed.exe

**Comment by zdm** [comment]
yes, i have the same

**Comment by mhinz** [comment]
Can you do `vim -V1 file` (on a file managed by hg with changes), then wait 3 seconds, and paste the complete output of `:messages`?

**Comment by zdm** [comment]
I didn't changed environment and configs for a years and everything is worked.
I will try to use more earlier signify versions.

**Comment by zdm** [comment]
```
Reading undo file: C:/Users/zdm/.vim/undo\d%%work%fbadbot%TODO.txt
not found in 'runtimepath': "indent/text.vim"
not found in 'runtimepath': "syntax/text.vim syntax/text/*.vim"
not found in 'runtimepath': "autoload/vimtex.vim"
[sy] Register new file: d:\work\fbadbot\TODO.txt
[sy:hg] get_diff_start()
[sy:hg] CMD: 'hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"'
[sy:hg] CMD DIR:  d:\work\fbadbot
[sy:hg] ORIG DIR: d:\work\fbadbot
[sy:git] get_diff_start()
[sy:git] CMD: 'git diff --no-color --no-ext-diff -U0 -- "TODO.txt"'
[sy:git] CMD DIR:  d:\work\fbadbot
[sy:git] ORIG DIR: d:\work\fbadbot
```

**Comment by mhinz** [comment]
Okay, so somehow Vim's `job_start()` seems to fail (which explains why `:SignifyDebug` works since it doesn't use `:h job_start()` but merely `:h system()`) otherwise you would have lines such as:

```
...
[sy:git] job_exit()
[sy:git] get_diff_cvs()
[sy:git] get_diff_end()
[sy:git] No valid diff found. Disabling this VCS.
[sy:hg] job_exit()
[sy:hg] get_diff_git()
[sy:hg] get_diff_end()
[sy:hg] set_signs()
[sy:hg] Signs updated.
```

**Comment by mhinz** [comment]
Oh, I found an issue in the plugin that explains why you don't see the messages.. I don't see them either in my Win VM, but that doesn't explain why no signs are shown.

**Comment by mhinz** [comment]
Can you confirm that the latest commit for vim-signify on your local disk is `c3f26e4`?

I wonder if you're missing https://github.com/mhinz/vim-signify/commit/b285820778d8f7987572168197a0d50dc335cf70

**Comment by zdm** [comment]
yes, latest commit is c3.

**Comment by mhinz** [comment]
Hmm, okay. Later, I'll install msys2 and see if I can reproduce it that way.

**Comment by zdm** [comment]
The problem is not in msys2, I already tested.

**Comment by mhinz** [comment]
Okay. Let's add some debugging lines..

Please insert `echomsg 'DEBUG ('. a:vcs .'): '. string(a:diff)` below this line: https://github.com/mhinz/vim-signify/blob/c3f26e459964617ffd21b3d50e0beeda22a7edd8/autoload/sy/repo.vim#L129

Then open a file with changes and paste all `DEBUG` lines from `:messages`.

**Comment by zdm** [comment]
Nothing was printed to log.

**Comment by mhinz** [comment]
Okay, then `echomsg 'FOO'` below https://github.com/mhinz/vim-signify/blob/c3f26e459964617ffd21b3d50e0beeda22a7edd8/autoload/sy/repo.vim#L35 and `echomsg 'BAR'` below https://github.com/mhinz/vim-signify/blob/c3f26e459964617ffd21b3d50e0beeda22a7edd8/autoload/sy/repo.vim#L43, please.

**Comment by zdm** [comment]
Nothing.

**Comment by mhinz** [comment]
Okay, this gives the expected diff, right?

```
:echo system('hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"')

**Comment by zdm** [comment]
Yes, the diff is correct.

**Comment by mhinz** [comment]
```vim
:echo job_start('hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"')
```

Does it say `process ... run`?

**Comment by zdm** [comment]
process 0 fail

**Comment by mhinz** [comment]
Aha! Now we must find out what's different between `system()` and `job_start()`.

Just to be on the safe side.. try another command that it guaranteed to success on Windows. Maybe `:echo job_start('dir')`? Does it say `... run`, now?

**Comment by zdm** [comment]
process 1232 run

**Comment by mhinz** [comment]
```
:echo join([&shell, &shellcmdflag, &shellxquote, 'CMD', &shellxquote])
```

**Comment by zdm** [comment]
C:\WINDOWS\system32\cmd.exe /c ( CMD (

**Comment by mhinz** [comment]
@chrisbra Sorry for interrupting you, but maybe you have quick idea about this:

With Vim 8.1.1413 on Windows (`shell=cmd.exe`), why would this succeed:

```vim
:echo system('hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"')
```

But the same string with `job_start()`...

```vim
:echo job_start('hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\work\fbadbot\TODO.txt"')
```

...result in `process 0 fail`?

I can't reproduce that with the same Vim version in my Win 10 VM, so I guess it's something environmental, but I lack Windows knowledge to pinpoint the actual issue. Any ideas?

**Comment by chrisbra** [comment]
Well for one, system() always runs the process using cmd.exe, while I believe `job_start` does not. 
Does it work if you run it through cmd.exe ? Might need to escape some of the arguments.

**Comment by mhinz** [comment]
@chrisbra Okay, thank you!

@zdm Please try replacing...

https://github.com/mhinz/vim-signify/blob/c3f26e459964617ffd21b3d50e0beeda22a7edd8/autoload/sy/repo.vim#L312

...by this...

```vim
        let cmd = join([&shell, &shellcmdflag, '(', vcs_cmd, ')'])
```

**Comment by zdm** [comment]
works

**Comment by mhinz** [comment]
Splendid!

Can you please double check that it also works if there are spaces in the filename?

**Comment by zdm** [comment]
yes, works, if filename contains spaces.

**Comment by mhinz** [comment]
Thanks for reporting this and helping me hunting down the issue!

(And thanks again for the pointer, chrisbra!)

**Comment by zdm** [comment]
Thanks for your work.
Good luck.

**Comment by zdm** [comment]
Yesterday it stop work again. The only thing, that I did - I updated vim to the latest patch.

**Comment by zdm** [comment]
I rolled back vim to v8.1.1413 and it start work again.

**Comment by zdm** [comment]
The problems started from vim patch v8.1.1417
patch 8.1.1417: MS-Windows: resolve() does not resolve all components of path
Problem:    MS-Windows: resolve() does not resolve all components of the path.
            (David Briscoe)
Solution:   Do not bail out for a reparse point. (Yasuhiro Matsumoto,
            closes #4211, closes #4447)

**Comment by chrisbra** [comment]
do you use a reparse point?

**Comment by zdm** [comment]
no

**Comment by zdm** [comment]
Is it possible to fix it?

**Comment by zdm** [comment]
I just checked, issue is not reproduced on the latest vim patch.
Sorry for disturbing you.
Best regards.
