### ISSUE TITLE
Error with new update!

### ISSUE THREAD

**Issue by mks1508** [mhinz/vim-signify#301]
Everytime I open a file from a modified git repo, my nvim showed this issue with new update:

![alt](https://i.imgur.com/UTTDpUd.png)

Seem like this issue come from **sy.vim** or **sign.vim**

![alt](https://i.imgur.com/juqnQXi.png)

I tried to download/use old version (Commits on May 29, 2019) ...and that version have no above issue.

**Comment by mhinz** [comment]
Argh, I missed that because I didn't have an autocmd set for `User Signify`/`User SignifySetup` while testing.

Thanks! ✨
