### ISSUE TITLE
Rearchitect signify to diff the buffer

### ISSUE THREAD

**Issue by kevincox** [mhinz/vim-signify#306]
*Note: This is work I think I have time to do, I just want to ensure it is welcome before starting.*

# Objective

There are a number of features that I would like to see in signify which don't seem easy/possible with the current VCS interface. I would like to adjust this slightly to support these feautres.

- Updates without saving buffer.
- [revert hunks](https://github.com/mhinz/vim-signify/issues/119)

Furthermore this will give us full control over the diff which should make parsing the diff simpler and allow for smarter diffing algorithms. This should transitively improve [diff preview](https://github.com/mhinz/vim-signify/issues/300) because of more flexible diffing (example, showing more context or using vim's diffing support).

Other posibilities unlcoked:
- Diff against any other file on the filesystem.
- Diff against the version of the file when opened.
- DIff against the file on disk. (unsaved changes)
- Cache base version for slow VCS (avoid hitting a remote server too often).

# Proposal

## VCS Interface

The proposal is quite simple, instead of asking the VCS to perform the diff we will just ask it to dump the "base" version of the file. This changes the VCS interface from diff to dump and will require reimplementing all of the current VCS commands. However since this interface is quite simple this should be easy to do. Furthermore we can support falling back to the old diff command until we add support for all VCS using the new system.

Example implementations:

```sh
git show :$file
hg cat $file
```

## Getting the Diff

The diff will be obtained by dumping both versions to disk and running the diff. Note that this doesn't require saving the buffer over top of the canonical verison of the file.

Additionally we now run the diff consistently across VCSs which gives us a lot of posibilities, including running different types of diffs for different things (for example diffing with context for previewing the change but without context for generating signs).

## Concerns

- Diffing locally can be faster than diffing remotely. There is the posibility for massive files transfering the diff from the server is faster. However this would require uploading the local version to the server so it is unlikely this would have better performance. Additionally this design opens the posibility of caching the base version so it will probably be faster if anything.
- Not all VCS support dumping the base version. This is possible but I have yet to see one. After all their whole job is storing revisions.
- The code would be hard to modify to implement this new interface. I haven't looked at the code so I have no idea.
- This would break user configs. If users have implemented custom diff commands then we would prefer these for a while. Eventually we may wish to deprecate support for this. Users will have to migration to the new API if they want the new features anyways.

**Comment by kevincox** [comment]
@mhinz Looks like you have started work on this for SignifyDiff.

**Comment by kevincox** [comment]
Looking into the code more it appears that most of the framework is there because there is already code for getting the base file for `:SignifyDiff`. I have a WIP which will diff against the buffer for these already-supported VCS and fall back to the disk-based diff for the others.

**Comment by mhinz** [comment]
Hi. I'm just back from vacation and will have a look at the PRs in the next days.

Thanks in advance for bringing this up again!

**Comment by kevincox** [comment]
Thanks. As you can see I ended up just implementing it. It seems to work
and the "get base version" code already existed for the diff feature. We
might want to put it behind a feature flag at least for beta testing in
case something goes wrong.

I'm on vacation myself now until October so I'll will be slow to respond
and won't be able to make changes until I'm back. So don't feel the need to
review urgently.

>
