### ISSUE TITLE
When a file is opened in a remote Vim server with --remote, signify always changes its current working directory

### ISSUE THREAD

**Issue by bfrg** [mhinz/vim-signify#312]
When a file is opened in a Vim server with `--remote`, signify changes the current working directory to the directory of the file.

**To Reproduce**
Run Vim as a server with server name `foo`:
```bash
cd ~/
vim --servername foo
```
In a second terminal open a file in this Vim server:
```bash
vim --servername foo --remote ~/path/to/some/randomfile
```
The current working directory changed from `$HOME` to `~/path/to/some/`. This occurs every time a file is opened through `--remote`. And it doesn't matter whether the file is part of a repository.

**Comment by mhinz** [comment]
I can reproduce it with different Vim versions, but I don't really see why this is happening. The code that changes back to the original directory _is_ executed and `getcwd()` is correct.

**Comment by mhinz** [comment]
It should work now. Thanks! ✨

**Comment by bfrg** [comment]
Yes it works. Thank you!
