### ISSUE TITLE
Error detected while processing function sy#util#refresh_windows

### ISSUE THREAD

**Issue by casr** [mhinz/vim-signify#318]
If I begin something in command mode by typing <kbd>:</kbd>, change my focus to another application and then return I receive:

```
Error detected while processing function sy#util#refresh_windows:
```

My setup is Vim 8.1.1048 running through tmux running through st.

I can reproduce it with this inside `~/.vim/vimrc`:
```vim
runtime defaults.vim
```

and then inside `.vim` you can clone these two plugins:
```sh
cd ~/.vim
git clone --depth 1 git://github.com/mhinz/vim-signify.git pack/auto/start/vim-signify
git clone --depth 1 git://github.com/tmux-plugins/vim-tmux-focus-events.git pack/auto/start/vim-tmux-focus-events
```

FYI the issue does not come up if I run Vim just through st so the issue might lie somewhere between tmux and `tmux-plugins/vim-tmux-focus-events`. I still thought it was worth raising the issue here.

**Comment by mhinz** [comment]
There should be additional lines, mentioning the actual issue, after:

```
Error detected while processing function sy#util#refresh_windows:
```

Please check `:messages`.

**Comment by casr** [comment]
Sorry, I didn't realise the message was clipped. Here it is in full from `:messages`:

```
Error detected while processing function sy#util#refresh_windows:
line    8:
E523: Not allowed here:     keepjumps windo if exists('b:sy') | call sy#start() | endif
```

`:SignifyRefresh` appears to function correctly.

**Comment by mhinz** [comment]
Hmm. Instead of sourcing vim-signify, just putting `autocmd FocusGained * windo ''` in the vimrc would be enough to reproduce this issue. Weirdly enough it only happens with Vim, not Nvim.

**Comment by mhinz** [comment]
Should work now!

**Comment by casr** [comment]
I've been able to test today and it looks like it's sorted. Thank you!
