### ISSUE TITLE
Error detected while processing function sy#start

### ISSUE THREAD

**Issue by spreiter** [mhinz/vim-signify#320]
Whenever I open I file, I get this message.
```
Error detected while processing function sy#start:
line   25:
E706: Variable type mismatch for: sy
```

I went back and it turns out, it was introduced in `fa4d4d6 Refactoring: propagate bufnr`

**Comment by haomingw** [comment]
I have the same issue `Error detected while processing function sy#start[13]..<SNR>87_skip`

**Comment by mhinz** [comment]
@haomingw There must be more to that error. Check `:messages`.

@spreiter Which Vim version? Which commit are you on? An error in line 25 means it's not master.

**Comment by haomingw** [comment]
```Error detected while processing function sy#util#refresh_windows[9]..sy#start[13
]..<SNR>90_skip:
line    8:
E15: Invalid expression: has_key(g:signify_skip_filetype, 'help') && getbufvar(a
:bufnr, '&buftype') == 'help')```
I am using neovim v0.3.8

**Comment by mhinz** [comment]
@haomingw What is your `g:signify_skip_filetype` set to?

**Comment by haomingw** [comment]
> g:signify_skip_filetype

let g:signify_skip_filetype = { 'journal': 1 }. I copied this config from somewhere.

**Comment by mhinz** [comment]
@spreiter Your issue (probably an old Vim) should be fixed on master.

**Comment by mhinz** [comment]
@haomingw Should be fixed on master!

**Comment by mhinz** [comment]
I could reproduce both of your issues and they should be fixed, so I'm closing this issue.

Thanks to both of you! ✨

**Comment by haomingw** [comment]
It works! Thank you @mhinz

**Comment by spreiter** [comment]
Yes, looks good. Thanks for the fast reply!! :)

**Comment by MicroNateId** [comment]
I don't think this is fixed -- at least not for my setup.  I always have to revert to an older version to get it to work. 

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 14 2019 10:43:10)
Included patches: 1-207, 209-629

Error detected while processing function sy#start..sy#repo#getdiff..<SNR>63_handle_diff..sy#sing#set_signs..sy#sign#process_diff..sy#sign#get_current_signs..sy#util#get_signs:
line    4:
E117: Unknown function: execute
