### ISSUE TITLE
Perforce has stopped working

### ISSUE THREAD

**Issue by AntonGitName** [mhinz/vim-signify#321]
I have pulled the latest version and it stopped working with perforce, but other VCSs might affected as well.

I noticed that `SignifyList` returns empty list for `vcs` and `SignifyDebug` simply does not run the diff command that I have specified for P4 with `g:signify_vcs_cmds`.

I looked into the code it looks like that the issue may be related to two a couple of changes:

*    `g:signify_vcs_list` does not exist anymore, so there is no way to force populate `s:vcs_list`
*     `s:vcs_list` is being filtered by `executable(v:var)` predicate (`perforce` is not an executable)

For example,
```
:echo filter(keys(g:signify_vcs_cmds), 'executable(v:val)')
['git', 'hg', 'rcs', 'svn', 'cvs']
```

The plugin works at `v1.9` though.

**Comment by mhinz** [comment]
Oops. You're absolutely right. The commit from earlier today mixed up `vcs_list` and `vcs_dict`.

Looking into it.

**Comment by mhinz** [comment]
Should work again now. Thanks! ✨
