### ISSUE TITLE
`:call sy#util#refresh_windows()` change the result of `:echo winnr('#')`

### ISSUE THREAD

**Issue by zgpio** [mhinz/vim-signify#322]

**Comment by mhinz** [comment]
Steps?

I can't reproduce it when I simply open two buffers (controlled by a VCS) in two windows. Then `winnr('#')` is the same before and after `:call sy#util#refresh_windows()`, no matter which window I'm in.

**Comment by zgpio** [comment]
This seems to have been fixed in the latest version.

**Comment by zgpio** [comment]
Thanks anyway, closed for now.

**Comment by zgpio** [comment]
Fixed by bca65bd Vim: avoid :windo in FocusGained handler.
