### ISSUE TITLE
Colors are not working on symbols

### ISSUE THREAD

**Issue by CristoAMH** [mhinz/vim-signify#324]
![Captura de pantalla 2019-11-02 a las 15 05 18](https://user-images.githubusercontent.com/39212295/68072931-0c467d00-fd83-11e9-9da7-7ddb87555df4.png)

As you can see in the left column it doesn't show the colors properly. It actually fills the background instead of the icon. Any idea?

I am using neovim v0.5 and Iterm2

**Comment by mhinz** [comment]
The plugin inherits the colors from the default highlighting groups `DiffAdd` etc. (`:hi DiffAdd`).

I hope `:h signify-colors` explains everything. If not, tell me what's missing.

By the way, `g:signify_sign_weight` and `g:signify_sign_color_inherit_from_linenr` were removed... 6 years ago. ;]
