### ISSUE TITLE
Only set autocmds if Signify is enabled

### ISSUE THREAD

**Issue by seanlaguna** [mhinz/vim-signify#325]
Signify will trigger autocmds even if it is disabled for a buffer. This isn't a huge problem but it does lead to a lot of extra autocmds running even if it's disabled or if I don't intend to be using it at all for this vim instance. I spent some time trying to figure out how to do this but my vim-fu isn't good enough to yield anything.

What triggered me to report this is that I use tmux with >1 tmux windows, and when I open vim in a window, do some stuff, and then switch windows, tmux alerts me of activity in the vim window because signify runs the `CursorHold` autocmds. Changing the `updatetime` to something small or disabling the `CursorHold` autocmds solves this annoyance as well, but it led me to realize that the autocmds are running and I think it's reasonable to try to find a way to keep them from triggering unless I want Signify to be actually showing me something. I'd ideally like Signify to completely lazily load until I type a Signify command or trigger a Signify `<Plug>` with a hotkey. when I *have* enabled Signify, I do love the autocmds and the small `updatetime`, so I'd like to have the best of both worlds here.

Any ideas?

**Comment by mhinz** [comment]
Right, currently we simply do `let b:sy.active = 0` for disabled buffers. Then, when the plugin is run, we bail out early: https://github.com/mhinz/vim-signify/blob/25f3d4b6faba8febfe67660194a966f3f27a2e9a/autoload/sy.vim#L49-L51

But I agree, there's no good reason going for not going even further and just dropping all autocmds for the current buffer when it gets disabled.

I'll change that.

**Comment by mhinz** [comment]
I quickly threw something together: https://github.com/mhinz/vim-signify/pull/326

Please test if you can break it. :)

**Comment by seanlaguna** [comment]
It looks to be working as desired with a single buffer, the non-ideal behavior I saw before is corrected (when signify is disabled, the autocmds are not there) and this is the case after toggling a few times in the same buffer. Here are two confounding sequences:

1. open file in buffer b1 in new vim instance (Sy disabled by default)
2. enable Sy for b1
3. open new buffer b2

b2 has Sy disabled, but the autocmds are there. Signify must be toggled twice to clear the autocmds (because it thinks it's disabled, so just doing `:SignifyDisable` is not enough.

1. open file in buffer b1 in new vim instance (Sy disabled by default)
2. enable Sy for b1
3. open new buffer b2
4. enable Sy for b2
5. disable Sy for b2
6. change back to b1

Signify will be showing the signs, but no autocmds will be enabled. Signify must be toggled twice to get back the autocmds (because it thinks it's enabled, so just doing `:SignifyEnable` is not enough.

Thanks a bunch for looking at this though! I see the idea for how to do it now. Let me take a look at the code to see if I can't see how to make sure the proper per-buffer behavior is preserved.

**Comment by mhinz** [comment]
> Signify will be showing the signs, but no autocmds will be enabled. Signify must be toggled twice to get back the autocmds (because it thinks it's enabled, so just doing `:SignifyEnable` is not enough.

The given example was fixed some time ago and I probably forgot to close this issue here. :-)

> I'm not super knowledgeable about the CursorHold movements, but it looks like moving the cursor in one buffer will trigger a CursorHold command in another buffer. As in, if I enable Sy and change buffers to one where Sy is not enabled, moving the cursor triggers the autocmd in the other buffer. That seems kind of strange to me, but I guess the event itself is not bound to the buffer, just the execution of the command is.

No, that's not the case. Easy to reproduce by opening 2 buffers in two windows and using something like this:

```vim
" buffer A
autocmd CursorHold * echomsg "FOO"

" buffer B
autocmd CursorHold * echomsg "BAR"
```

Moving around in buffer B will never trigger the "FOO" message and vice versa.

I don't see any more to act on, so I'm closing this. Thanks for the bug report!
