### ISSUE TITLE
Macvim redraw removes echo messages

### ISSUE THREAD

**Issue by Freedzone** [mhinz/vim-signify#328]
Hello.
I've noticed that on Macvim, when signify is running, echo messages are getting removed every `updatetime`. That can be particularly annoying when running plugins like ALE. I found it is caused by `redraw` call for Macvim in the `sign.vim` - `call feedkeys("\<c-l>", 'n')`. I ve commented this line and have not noticed any problems. What cases does this logic cover? Maybe it was some bug in macvim in the past and can be safely removed now? I know it is possible to remove autocmd for cursorhold, but i like real time update feature very much.

**Comment by mhinz** [comment]
You're absolutely right. I played around with MacVim a bit and couldn't reproduce it anymore.

Thanks for letting me know!
