### ISSUE TITLE
Is there any function that shows me git branch name?

### ISSUE THREAD

**Issue by nnorakk** [mhinz/vim-signify#329]
Hi, It's just a help here

Is there any function that get me the branch name? like https://github.com/itchyny/vim-gitbranch ?

**Comment by mhinz** [comment]
Nope. :)

This plugin tries to avoid VCS-specific features on purpose. For the same reason there's no support for `git revert` etc.

Personally I use `:echo fugitive#head()` (from [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive)) in my statusline.
