### ISSUE TITLE
Usage without version control systems

### ISSUE THREAD

**Issue by ProudPenguin** [mhinz/vim-signify#330]
This issue is more like a question and I don't know if it is appropriate to ask questions here on GitHub. Please let me know. ;)

Imagine I have a file that is not managed by a version control system. I could create a temporary copy of this file and run the `diff --color=never -U0 %f temporary-file` command to review my changes. So I would like to know if such a use case is supported by this plugin?

I found the two variables `g:signify_vcs_cmds` and `g:signify_vcs_cmds_diffmode` in the documentation which probably needs to be modified. What are my options to change the path to the _temporary file_ on a per buffer case?

**Comment by KapJI** [comment]
I think using these variables you can define custom vcs and use some suffix to define filename of file you want to compare current buffer to. Like this:
```vim
let g:signify_vcs_cmds = {'custom': 'diff -U0 %f_custom.txt %f'}
let g:signify_vcs_cmds_diffmode = {'custom': 'cat %f_custom.txt'}
```

**Comment by jamessan** [comment]
Closing since the use case seems to be addressed by @KapJI's comment.
