### ISSUE TITLE
How to stage a hunk?

### ISSUE THREAD

**Issue by aganm** [mhinz/vim-signify#332]
I can't find how to stage a hunk in the manual. I thought there would be a function called SignifyStageHunk but no luck. How do I do that with signify?

**Comment by cumulotimbus** [comment]
See https://github.com/mhinz/vim-signify/issues/119.

tl;dr not gonna happen. 😞

**Comment by timbedard** [comment]
See https://github.com/mhinz/vim-signify/issues/119.

**Comment by nomasprime** [comment]
Thought about this too and, while it seems convenient, it's a lot of extra functionality to add and maintain across multiple interfaces.

Personally think there's more value in accessing non-editor related functionality directly most of the time anyway. The only exception these days is `Gdiff` but might even pull that out.

**Comment by jamessan** [comment]
Duplicate of #119
