### ISSUE TITLE
Signify doesn't show SVN code status in sign column

### ISSUE THREAD

**Issue by yehudat** [mhinz/vim-signify#335]
Version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:26) Included patches: 1-207, 209-629
Doesn't work: set signcolumn=yes "or "yes"
:!svn diff - works
:SyDebug - "Not an editor command"
:echo SignifyDebugListActiveBuffers() - show the changes monitored by the plugin. It seems to be an issues of the presentation.

**Comment by jamessan** [comment]
> :SyDebug

The command is `:SignifyDebug`, however as described in README.md you need at least Vim 8.0.902 to use the master branch.  If you're stuck with an older Vim, you should run from the `legacy` branch.

**Comment by yehudat** [comment]
Hi,
Thanks for the reply. Would you send me a link to the legacy branch? I don’t see it on GitHub. I’m stuck with VIM7.4 :(

Best regards,
YT

**Comment by jamessan** [comment]
> Would you send me a link to the legacy branch?

Hmm, I guess the README is wrong.  The pre-async code _was_ kept.

In that case, can you post the output of `:verbose w` for a file that isn't displaying signs properly?

**Comment by yehudat** [comment]
> > Would you send me a link to the legacy branch?
> 
> Hmm, I guess the README is wrong. The pre-async code _was_ kept.
> 
> In that case, can you post the output of `:verbose w` for a file that isn't displaying signs properly?

**Comment by yehudat** [comment]
I ran verbose w and it prints:
“dir_name/file_name Line, Column written”

I use VIM8.1 now

**Comment by jamessan** [comment]
If you're still seeing this issue, could you run `vim -V1 some_file` and then show the output of `:filter /\[sy/ messages`?

**Comment by mhinz** [comment]
It was not just an old Vim version, but `SignifyDebugListActiveBuffers()` was removed 8 years ago, so the plugin was heavily out-of-date.

I also see that you switched to gitgutter in the meanwhile, so there probably won't be much activity in here anyway.

Thanks anyway. Closing!

**Comment by yehudat** [comment]
Hi,
Not sure, what you are suggesting. Is there any solution available?

Regards,
Yehuda Tsimanis
