### ISSUE TITLE
Error when deleting a folder

### ISSUE THREAD

**Issue by kassio** [mhinz/vim-signify#336]
Steps to reproduce:
1. Open nvim
1. Open a file
1. Delete the folder that contains the opened file, nerdtree or other shell
1. Come back to the window of the file
1. Observe the error:
```
Error detected while processing function sy#util#refresh_windows[9]..sy#start[65]..sy#repo#get_diff:
line   19:
E475: Invalid argument: expected valid directory
```

_Originally posted by @kassio in https://github.com/mhinz/vim-signify/issues/333#issuecomment-617816174_

**Comment by jamessan** [comment]
This is due to 16eee41d2b267523b84bd4ac111627588bfd1a47, which disabled the `filereadable()` check (by only calling `s:skip()` for new buffers).  #344 should fix this, but I'd like @mhinz to chime in, since he made the change mentioned above.
