### ISSUE TITLE
How do I change the sign priority?

### ISSUE THREAD

**Issue by sbromberger** [mhinz/vim-signify#337]
vim-signify is clobbering neovim's LSP signs. With vim-gitgutter it's possible to set a priority for the git indicator signs so that they don't interfere with LSP. Is it possible to do that with vim-signify? Thanks.

**Comment by sbromberger** [comment]
What's interesting (after having read through https://github.com/mhinz/vim-signify/pull/331) is that the neovim LSP signs aren't showing up via `:sign place`. I don't know how they're being rendered.

**Comment by kutsan** [comment]
neovim's default LSP sign priority is `10` and I think signify's default priority should be `0`. It always needs to in background over other signs.

**Comment by timbedard** [comment]
I don't mind if being 10 by default, but should definitely be configurable. Right now, it looks like signify doesn't even pass the priority when placing a sign.

On the topic: Is there a reason that the current code is executing the `sign place` command rather than the `sign_place()` function?

**Comment by jamessan** [comment]
> On the topic: Is there a reason that the current code is executing the `sign place` command rather than the `sign_place()` function?

Compatibility.  I think it would be good to support, particularly the variant that let's you place a list of signs, but I'm not sure we should require the new API yet.

This is on my list of things to look into as I have time.

**Comment by timbedard** [comment]
@jamessan I whipped up a quick PR with a simple implementation when you have some time to take a peek.
