### ISSUE TITLE
issue with mphe/grayout.vim

### ISSUE THREAD

**Issue by rwmitchell** [mhinz/vim-signify#338]
grayout plugin changes the font/color of text inside a disabled #ifdef block.
If that block coincides with vcs changed text, the highlight text by grayout is undone.

I think I'm mostly using the defaults in both, I don't have SignifyToggleHighlight enabled.  I'm using it with 'hg' but I doubt that is the issue.

:GrayoutUpdate initially changes the highlight of the disabled text, until updatetime expires and then the change is undone and replaced with the normal coloring.  I had assumed Signify was only modifying the gutter, but it must be triggering a reset for the entire line.

vim-signify is awesome, so I apologize for this sounding like I'm complaining.

**Comment by jamessan** [comment]
Both plugins use the `linehl` functionality of signs, although Sy only does by request (`let g:signify_line_highlight = 1`).  One of them is going to win out when they're both enabled.  If you'd rather have grayout's line highlighting, then I'd make sure `g:signify_line_highlight` is 0.

If it's still not working with that, then this is probably another issue related to how Sy currently handles multiple signs on the same line.

Both vim and nvim have improved handling of multiple signs on the same line, so Sy should probably be updated to account for that.

It may also be worth defining completely separate signs with and without line highlighting to try and avoid overlap with other plugins.

**Comment by rwmitchell** [comment]
g:signify_line_highlight is set to 0.  I've set it both manually and using SignifyToggleHighlight.  When it is set, the background color changes.

**Comment by jamessan** [comment]
Does this help at all?

```diff
diff --git i/autoload/sy/highlight.vim w/autoload/sy/highlight.vim
index 58ac0bb..138f534 100644
--- i/autoload/sy/highlight.vim
+++ w/autoload/sy/highlight.vim
@@ -39,9 +39,9 @@ endfunction
 
 " #line_disable {{{1
 function! sy#highlight#line_disable() abort
-  execute 'sign define SignifyAdd text='. s:sign_add 'texthl=SignifySignAdd linehl='
-  execute 'sign define SignifyChange text='. s:sign_change 'texthl=SignifySignChange linehl='
-  execute 'sign define SignifyRemoveFirstLine text='. s:sign_delete_first_line 'texthl=SignifySignDeleteFirstLine linehl='
+  execute 'sign define SignifyAdd text='. s:sign_add 'texthl=SignifySignAdd'
+  execute 'sign define SignifyChange text='. s:sign_change 'texthl=SignifySignChange'
+  execute 'sign define SignifyRemoveFirstLine text='. s:sign_delete_first_line 'texthl=SignifySignDeleteFirstLine'
   let g:signify_line_highlight = 0
 endfunction
 
diff --git i/autoload/sy/sign.vim w/autoload/sy/sign.vim
index 844d245..ba961fb 100644
--- i/autoload/sy/sign.vim
+++ w/autoload/sy/sign.vim
@@ -10,7 +10,7 @@ else
 endif
 
 let s:sign_show_count  = get(g:, 'signify_sign_show_count', 1)
-let s:delete_highlight = ['', 'SignifyLineDelete']
+let s:delete_highlight = ['', 'linehl=SignifyLineDelete']
 " 1}}}
 
 " #id_next {{{1
@@ -224,7 +224,7 @@ function! s:add_sign(sy, line, type, ...) abort
   endif
 
   if a:type =~# 'SignifyDelete'
-    execute printf('sign define %s text=%s texthl=SignifySignDelete linehl=%s',
+    execute printf('sign define %s text=%s texthl=SignifySignDelete ',
           \ a:type,
           \ a:1,
           \ s:delete_highlight[g:signify_line_highlight])
```

**Comment by rwmitchell** [comment]
That works beautifully!  Much thanks!!

**Comment by jamessan** [comment]
Unfortunately, that doesn't solve the problem.  It just shows that the plugins _can_ co-exist. :) In order to support toggling line highlighting, we need to specify an empty `texthl` when re-defining the sign.

We may need to take a different approach for toggling highlighting.

**Comment by rwmitchell** [comment]
After using the patch, I've noticed the gutter marks do not go away after a commit.

I've tried SignifyToggle (twice) which makes them go away, but marks for new changes do not appear.

SignifyDisable/Enable doesn't help.

SignifyDebug shows it is trying git/svn/hg with results for the last, which is kinda unexpected as I've set:
let g:signify_vcs_list = [ 'hg' ]
but I'm assuming Debug ignores that.

SignifyList shows:

    active  =  1
    buffer  =  1
       vcs  =  ['hg']
     stats  =  -1 added, -1 changed, -1 removed
    signid  =  337
     hunks  =  []

Looks like it should be working.

Reloading the file ( :e! ) does not help, but closing and reopening that MacVim window does.
I'm guessing since you said this doesn't solve the problem, these issues were expected?
Obviously I didn't look closely at the patch.

ps: why do people who go in "great" detail about a problem usually only show how little they understand and their effort t be helpful usually isn't.  that probably applies here.

**Comment by jamessan** [comment]
https://github.com/mhinz/vim-signify/pull/343 should work better, if you're using a new enough (n)vim.  For older (n)vim versions, more substantial changes would be needed.

**Comment by rwmitchell** [comment]
vim needs more gutter.

Signify gutter symbols work great!  However, they now overwrite symbols added by YCM indicating bad code.

**Comment by jamessan** [comment]
> However, they now overwrite symbols added by YCM indicating bad code.

You can change the priority of Sy's signs using the `g:signify_priority` variable.  Currently, Sy creates signs at the default priority (10).  If you lower that in your vimrc, then other plugins which use the default priority will take precedence.

**Comment by rwmitchell** [comment]
I tried setting at the command line with:
`  :let g:signify_priority=1
`
but it didn't appear to have any effect.  I checked settings for ycm but didn't see anything with 'priority' in the name.

I'm more than happy how things work, just an observation.

**Comment by jamessan** [comment]
So this issue is handled now?

**Comment by rwmitchell** [comment]
signify and ycm still clash with signify winning, but suspect the solution involves a change to ycm instead.

For my code, I keep the status line free (as in resolving them, not that there are never any) of errors/warnings as reported by ycm.  If any occur, they must therefor also be in changed code, which I also try to keep to minimum in between commits.
