### ISSUE TITLE
Error detected while processing function callback_vim_close

### ISSUE THREAD

**Issue by cradesto** [mhinz/vim-signify#340]
After the may 15 commit the error occurs on linux.

```
Error detected while processing function <SNR>98_callback_vim_close[9]..<SNR>98_handle_diff[31]..sy#sign#set_signs[20]..sy#sign#process_diff[69]..<SNR>111_add_sign:
line   25:
E474: Invalid argument
```

It seems that there is no error on mac machine.

**Comment by jamessan** [comment]
What are the Vim versions on the two systems?

**Comment by cradesto** [comment]
linux: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
mac: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 13 2020 16:28:49)

**Comment by jamessan** [comment]
Ok, I see the problem. Will fix it later today.
