### ISSUE TITLE
Undo deleted lines mixes order

### ISSUE THREAD

**Issue by TelManuel** [mhinz/vim-signify#345]
I am pretty sure, that this one cannot be a general issue and it is related to my environment.

Starting point:
``` 
    1 line1
    2 line2
    3 line3
    4 line4
```

I delete line 3:
```
    1 line1
_1  2 line2
    3 line4
```

`:SignifyHunkDiff` on line 2 shows:
```
    1 -line3
```

If I now do `:SignifyHunkUndo` on line 2, I get:
```
_1  1 line1
    2 line3
+   3 line2
    4 line4
```

Deleted line is added above although it was deleted below. So the order is not correct anymore.

Not to deep into it, so I simply changed `vim-signify/autoload/sy/repo.vim` like this:
```
! 424       call append(new_line, text)
```

without being confident, this is it. In the end, it fixed the actual issue, but with this revoking changes on a line does not work any longer:

```
    1 line1
!   2 Line2
    3 line3
    4 line4
```

Hunk:
```
    1 -line2
    2 +Line2
```

Undo:
```
    1 line1
+   2 Line2
    3 line2
    4 line3
    5 line4
```

Error:
```
Error detected while processing function <SNR>59_callback_vim_close[9]..<SNR>59_handle_diff[31]..<SNR>59_undo_hunk:
line   24:
Could not apply addition hunk for undo. Try saving the buffer first.                                                              
```

Anyhow, probably it is a special issue on my environment and someone can help me to find out, what is wrong. In the other case, no one is apparently using the undo to get back deleted lines 🙂

**Comment by Arnie97** [comment]
I can reproduce this issue on nvim v0.3.4, nvim 0.4.3 and vim 8.1.2292.

**Comment by jumpnbrownweasel** [comment]
Happens for me also, in many cases.

**Comment by jumpnbrownweasel** [comment]
Does anyone know of a workaround?

**Comment by SanchayanMaity** [comment]
Have observed this every time for an one line change. Undo hunk just works incorrectly in that case as described.

**Comment by calid** [comment]
same for me

**Comment by noscript** [comment]
Same here.
