### ISSUE TITLE
Not updating on Cursor autocmds

### ISSUE THREAD

**Issue by nomasprime** [mhinz/vim-signify#346]
Think this was working before but since updating everything recently Cursor related autocmds don't seem to be working.

I'm on NeoVim, latest versions of everything.

PS Thanks for a great plug-in.

**Comment by nomasprime** [comment]
OK, I was using using NeoVim default, ie, not explicitly setting `updatetime`. If I set explicitly, it starts working again.

**Comment by mhinz** [comment]
Yup, it both Nvim and Vim default to 4 seconds by default.

I guess this can be closed. :)

**Comment by nomasprime** [comment]
Hey @mhinz, to be clear, Signify doesn't update for me without `updatetime` being set explicitly in my `init.vim`, ie, with defaults Signify doesn't seem to update on `updatetime` related autocmds. Not sure if this is a bug or expected behaviour?

**Comment by mhinz** [comment]
It's been some time.. but I learned that Nvim has issues with the cursor events in certain cases: https://github.com/neovim/neovim/issues/12587

So, could you try with Vim?

**Comment by glepnir** [comment]
You can try the plugin in the comments, it worked for me.👌

**Comment by nomasprime** [comment]
@mhinz Don't have a Vim config at hand but installing the plug-in should indicate if it's an editor issue, not signify.

@glepnir Thanks, was unaware of this issue. That plug-in looks great, hoping for a general performance bump 🤞 

If the issue persists, I'll port a Vim config and report back but otherwise it can be considered resolved.
