### ISSUE TITLE
b:sy is empty after SignifyDiff

### ISSUE THREAD

**Issue by Shane-XB-Qian** [mhinz/vim-signify#347]
not sure if related to my env, but once i ran one SignifyDiff, then next such cmd failed.

i looked into src code a bit, looks `b:sy` was empty after then, 
then `sy#util#return_if_no_changes()` is 'return' ..

so once i switch from a SignifyDiff tab back to original tab, 
the ~~highlight~~ **signcolumn** was gone, and can not do SignifyDiff again.

perhaps was a bug (let sy = .. ?), or i miss-understood sth .. as a workaround, a ':e' helped, though ..

vim 8.2.983

**Comment by Freed-Wu** [comment]
i met a similar problem:
```
|| Error detected while processing function
|| sy#util#refresh_windows[9]
|| sy#start[51]
|| sy#stop[3]
|| sy#sign#remove_all_signs[3]
|| E716: Key not present in Dictionary: hunks
|| Error detected while processing function
|| sy#util#refresh_windows[9]
|| sy#start[51]
|| sy#stop[3]
|| sy#sign#remove_all_signs[3]
|| E15: Invalid expression: sy.hunks
```

i recommend to add some code to distinguish whether b:sy is an empty dictionary.
