### ISSUE TITLE
Signify Disables Itself After Running SignifyDiff

### ISSUE THREAD

**Issue by yarko3** [mhinz/vim-signify#351]
1. I make a change
2. I see Signify markings in the left column
3. I run :SignifyDiff()
4. I quit out of the Signify-openned buffers
5. I no longer see Signify markings in the left column

I have to run SignifyToggle or SignifyEnable to get the column markings to show again. This smells like it's related to https://github.com/mhinz/vim-signify/pull/326

My config is here: https://github.com/yarko3/dotfiles/blob/master/vimrc

**Comment by Shane-XB-Qian** [comment]
fyi: pls refer #347 perphas same, and a pr sent by @jamessan , but just have not merged yet. :)

**Comment by yarko3** [comment]
Hello? This is still an ongoing problem.

**Comment by jamessan** [comment]
Can you please re-test with the latest changes?

**Comment by yarko3** [comment]
All fixed now! Thanks for your PR.
