### ISSUE TITLE
change diff base

### ISSUE THREAD

**Issue by stumash** [mhinz/vim-signify#354]
feature request:
show gutter diffs against another branch, like master, instead of the last commit

it's a big one, I know

**Comment by jamessan** [comment]
If you're talking about the signs, then you can do this by changing `g:signify_vcs_cmds` to compare against the respective branch.  Similarly, for `:SignifyDiff`, you can change `g:signify_vcs_cmds_diffmode`.

**Comment by stumash** [comment]
just for bookkeeping in case somebody else comes across this PR and is looking for a one-liner:

the default values for the relevant signify global variables at the time of this comment are:
```viml
let g:signify_vcs_cmds.git = "git diff --no-color --no-ext-diff -U0 -- %f"
let g:signify_vcs_cmds_diffmode.git = "git show HEAD:./%f"
``` 

I created the following convenience function to toggle between the default git calls and the ones which would cause signify gutter signs to diff against the master branch instead of the last commit:

```viml
let g:signify_against_master = 0
function SignifyMaster()
    if g:signify_against_master
        let g:signify_vcs_cmds.git = "git diff --no-color --no-ext-diff -U0 -- %f"
        let g:signify_vcs_cmds_diffmode.git = "git show HEAD:./%f"
        let g:signify_against_master = 0
    else
        let g:signify_vcs_cmds.git = "git diff master --no-color --no-ext-diff -U0 -- %f"
        let g:signify_vcs_cmds_diffmode.git = "git show master:./%f"
        let g:signify_against_master = 1
    endif
endfunction
nmap <leader>gm :call SignifyMaster()<CR>
```
