### ISSUE TITLE
signs don't show on folded lines

### ISSUE THREAD

**Issue by bart9h** [mhinz/vim-signify#355]
If a fold is closed, I can't see if there's any modifications inside it.

Is this possible?

**Comment by teto** [comment]
should be possible on neovim master. Note that the folds display is buggy if you enable `spell` (for now).

**Comment by jamessan** [comment]
> should be possible on neovim master.

If it's the first line of the fold that is modified, that's true.  However, there would need to be significant changes in the plugin to support aggregating the information about _all_ of the lines encompassed by the fold into a single sign.

I'm not even sure if that's possible, given there aren't any notifications about opening/closing folds.
