### ISSUE TITLE
Hide signs without disabling the plugin

### ISSUE THREAD

**Issue by maujim** [mhinz/vim-signify#356]
### Desired behaviour
Is it possible to add in a feature to hide the signs without disabling the full plugin, i.e a `:SignifyToggleSigns` command. 

### Motivation
I would like to have the stats show up in the statusline but not have the signs until I need them and currently the only way to "hide" the signs is to disable the plugins which causes the statusline function to display blank text.

**Comment by jamessan** [comment]
Since the entire purpose of the plugin is to display signs, and the stats are just an added benefit, I don't think it's worth complicating the code for this.

You can use `:set signcolumn=no` to avoid displaying the sign column when you don't want it.
