### ISSUE TITLE
SignifyHunkUndo doesn't work when first line has a deletion hunk

### ISSUE THREAD

**Issue by jamischarles** [mhinz/vim-signify#357]
When I delete the first line, I can run `SignifyHunkDiff` to show me the diff, but `SignifyHunkUndo` has no effect. If I modify the line (instead of deletion) `SignifyHunkUndo` works again.

![Kapture 2020-10-17 at 00 40 38](https://user-images.githubusercontent.com/606014/96330303-6894c200-1011-11eb-8d39-1360d1a89071.gif)

**Comment by KapJI** [comment]
This is fixed by #362
