### ISSUE TITLE
Any way to change the colors on the hunkdiff?

### ISSUE THREAD

**Issue by jamischarles** [mhinz/vim-signify#358]
I'd really love to change these colors, esp the background color. Any ideas for how to accomplish that? 
<img width="591" alt="Screen Shot 2020-10-17 at 12 37 26 AM" src="https://user-images.githubusercontent.com/606014/96330227-f02e0100-1010-11eb-9012-196ec99930df.png">

**Comment by KapJI** [comment]
This highlighting is defined by your theme for `diff` syntax.
You can change `diffAdded` and `diffRemoved` hightlights manually.
For example:
```
highlight diffAdded guifg=green
highlight diffRemoved guifg=red
```
