### ISSUE TITLE
Show delete count number only greater one

### ISSUE THREAD

**Issue by weilbith** [mhinz/vim-signify#359]
Hey,
I would like to ask if it would be possible to show the number for `signify_sign_show_count` only when it is greater than one. If there is only one line removed, there is already the sign to show it. If there are 2 or more, then the number of the count helps, because there can't really be an indicator for that information else.
Would be pretty cool.
Thank you very much!

**Comment by weilbith** [comment]
I switched to the `lewis6991/gitsigns.nvim` plugin. So this is no more an issue for me. As nobody else seem to be interested, I'll just close this issue for now.

**Comment by Shane-XB-Qian** [comment]
perhaps meaningless (or cannot) put too much things there.. IMO.
or perhaps neovim could? no chance to try yet..

but i guess `sy#repo#get_stats()` is actually what you wanted.

// this repo is quiet long time.. :-) and looks this is not a bug, perhaps that's why no one interesting to answer... :-)

**Comment by jamessan** [comment]
> I would like to ask if it would be possible to show the number for `signify_sign_show_count` only when it is greater than one.

This seems reasonable to me.
