### ISSUE TITLE
Error on open file with 'Error detected while processing function <SNR>75_callback_nvim_exit[1]'

### ISSUE THREAD

**Issue by hoanghun** [mhinz/vim-signify#366]
Opening existing file sometimes outputs error:

```
Error detected while processing function <SNR>83_callback_nvim_exit[1]..<SNR>83_handle_diff[31]..sy#sign#set_signs[17]..sy#highlight#line_disable:
line    3:
E239: Invalid sign text:

```

Using neovim with this version:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20201103-57912-svovf1/neovim-0.4.4/build/config -I/tmp/neovim-20201103-57912-svovf1/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20201103-57912-svovf1/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201103-57912-svovf1/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20201103-57912-svovf1/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"
```

Plugin currently doesn't show colors in gutter.

**Comment by dohq** [comment]
same with vim...
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  2 2021 14:41:35)
Included patches: 1-2451
```

**Comment by basicBrogrammer** [comment]
I reset to d80e507 and the error went away. It appears that b2a0450  is where the error was introduced. Hope that helps 👍

**Comment by jamessan** [comment]
Does everyone experiencing this problem `'ambiwidth'` set to double?

**Comment by yylogo** [comment]
> Does everyone experiencing this problem `'ambiwidth'` set to double?

my 'ambiwidth' is double

**Comment by Shane-XB-Qian** [comment]
that char '‾' len is 3, so perhaps even ambiwidth did not help?
// i didnot expeirenced/reproduced this, so just a guess...

// @jamessan pls help to review/handle #365 as well.... thx.

**Comment by wdv4758h** [comment]
> I reset to [d80e507](https://github.com/mhinz/vim-signify/commit/d80e507c8ba31d7d0711eb3b9a8053ec5f01df5c) and the error went away. It appears that [b2a0450](https://github.com/mhinz/vim-signify/commit/b2a0450e23c63b75bbeabf4f0c28f9b4b2480689) is where the error was introduced. Hope that helps +1

I update my plugins and hit this issue today. Thanks for pointing out the working version!

**Comment by Shane-XB-Qian** [comment]
pls check my last refined comment, looks you No need to reset version,
just try to chg that mark char as workaround if your ambiwidth was double............

// though perhaps if this plugin can auto fit the char per that option value would be better................

**Comment by sunowsir** [comment]
In this code file: `/home/sunowsir/.config/nvim/plugged/vim-signify/autoload/sy/highlight.vim `, I change a symbol in a single quotation mark in this line `  let s:sign_delete_first_line = get(g:, 'signify_sign_delete_first_line', '-')
`, everything is ok!

**Comment by imbible** [comment]
@Shane-XB-Qian Unfortunately your fix is not working on my vim. It still gives below errors -
Error detected while processing function <SNR>142_callback_vim_close[9]..<SNR>142_handle_diff[31]..sy#sign#set_signs[17]..sy#highlight#line_disable:
line    3:
E239: Invalid sign text: ~^^

BTW, my 'ambiwidth' is single.

**Comment by Shane-XB-Qian** [comment]
IMO : No req (or donot set) if 'single'.

**Comment by imbible** [comment]
@Shane-XB-Qian Thanks for your solution. It works.

**Comment by jamessan** [comment]
> In this code file: `/home/sunowsir/.config/nvim/plugged/vim-signify/autoload/sy/highlight.vim `, I change a symbol in a single quotation mark in this line ` let s:sign_delete_first_line = get(g:, 'signify_sign_delete_first_line', '-')`, everything is ok!

There's no reason to modify the plugin.  Just set your own sign -- `let g:signify_sign_change_delete = '<whatever>'`.

**Comment by jamessan** [comment]
https://github.com/mhinz/vim-signify/pull/368 avoids the error by detecting if the sign is too wide and changing it to a safe value.

This is just to avoid the error from popping up since the default value can be problematic in certain configs.  The true fix is for people to set the value to something they like that abides by the "two column" limit for signs.

**Comment by jose4125** [comment]
> > I reset to [d80e507](https://github.com/mhinz/vim-signify/commit/d80e507c8ba31d7d0711eb3b9a8053ec5f01df5c) and the error went away. It appears that [b2a0450](https://github.com/mhinz/vim-signify/commit/b2a0450e23c63b75bbeabf4f0c28f9b4b2480689) is where the error was introduced. Hope that helps +1
> 
> I update my plugins and hit this issue today. Thanks for pointing out the working version!

@basicBrogrammer  Hi, How Did you reset to a specific commit?

**Comment by basicBrogrammer** [comment]
> > > I reset to [d80e507](https://github.com/mhinz/vim-signify/commit/d80e507c8ba31d7d0711eb3b9a8053ec5f01df5c) and the error went away. It appears that [b2a0450](https://github.com/mhinz/vim-signify/commit/b2a0450e23c63b75bbeabf4f0c28f9b4b2480689) is where the error was introduced. Hope that helps +1
> > 
> > I update my plugins and hit this issue today. Thanks for pointing out the working version!
> 
> @basicBrogrammer  Hi, How Did you reset to a specific commit?

Im using vim plug. So I went into my plug directory where the plugin repos are then to the vim signify dir. From there I just did a git reset to that sha.

**Comment by sunowsir** [comment]
> > In this code file: `/home/sunowsir/.config/nvim/plugged/vim-signify/autoload/sy/highlight.vim `, I change a symbol in a single quotation mark in this line ` let s:sign_delete_first_line = get(g:, 'signify_sign_delete_first_line', '-')`, everything is ok!
> 
> There's no reason to modify the plugin. Just set your own sign -- `let g:signify_sign_change_delete = '<whatever>'`.

thank you for your reply
