### ISSUE TITLE
"!" symbol showing up instead of "+"

### ISSUE THREAD

**Issue by saahiluppal** [mhinz/vim-signify#372]
Here is the screenshot of my concern
[![Screenshot](https://raw.githubusercontent.com/saahiluppal/saahiluppal/main/assets/vim-signify-issue.png)]

If this is alright, then how can i change this symbol back to "+", because "!" symbol is kinda annoying to me and is difficult to interpret when this is in front of multiple lines

**Comment by mhinz** [comment]
The `:h signify-signs`. `!` is used for modified lines.

Change it like this:

```
let g:signify_sign_change = '~'
```
