### ISSUE TITLE
Error detected while processing function  line    3: E239: Invalid sign text:

### ISSUE THREAD

**Issue by jose4125** [mhinz/vim-signify#374]
hi I updated today my plugins, and I'm getting an error

```
Error detected while processing function <SNR>184_callback_nvim_exit[1]..<SNR>184_handle_diff[31]..sy#sign#set_signs[17]..sy#highlight#line_disable:
line    3:
E239: Invalid sign text:

```
```
I'm using 
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
```

on my init.vim I added the line below but doesn't work.
` let g:signify_sign_delete_first_line = '-'`

thanks.

**Comment by mhinz** [comment]
- When do you get that error?
- What is your plugin configuration?

**Comment by jose4125** [comment]
I'm getting that error when I opened any file, an empty file or files with code on it.
this is the plugin configuration

```
let g:signify_sign_show_text = 0
let g:signify_sign_delete_first_line = '-'

highlight SignifySignAdd                  ctermbg=green                guibg=#00ff00
highlight SignifySignDelete ctermfg=black ctermbg=red    guifg=#ffffff guibg=#ff0000
highlight SignifySignChange ctermfg=black ctermbg=yellow guifg=#000000 guibg=#ffff00
```

**Comment by jamessan** [comment]
There's no reason this should happen in an empty file, since Sy won't be placing any signs then.

Try starting nvim and then running `:verbose e somefile`, where `somefile` is a file that causes the problem.  Since https://github.com/mhinz/vim-signify/pull/368, this should display a message showing the string that's too large for the two columns that a sign is allowed to occupy.

**Comment by mhinz** [comment]
Actually.. I can reproduce it with only `let g:signify_sign_show_text = 0` set in any VCS-controlled file with Nvim 0.4.4 and Vim master (!), but not Nvim master.

**Comment by jamessan** [comment]
Seems like a general problem, which 60a27c5 may have exposed.  If we're not showing text for signs, then we either should not specify `text` and `texthl` or we need to use `text=\ ` to set text to a space.

**Comment by mhinz** [comment]
Yup, this would probably be the easiest:

```diff
diff --git i/autoload/sy/highlight.vim w/autoload/sy/highlight.vim
index 6da5b82..d715f54 100644
--- i/autoload/sy/highlight.vim
+++ w/autoload/sy/highlight.vim
@@ -16,4 +16,4 @@ else
-  let s:sign_add               = ' '
-  let s:sign_delete_first_line = ' '
-  let s:sign_change            = ' '
-  let s:sign_change_delete     = ' '
+  let s:sign_add               = '\ '
+  let s:sign_delete_first_line = '\ '
+  let s:sign_change            = '\ '
+  let s:sign_change_delete     = '\ '
```

But maybe `g:signify_sign_show_text` was a mistake from the beginning. I think it would be less confusing (and less code), if we just removed that option, and add a few common unicode characters to the doc instead.

I mean, most people using that option probably just want this instead:

```vim
let g:signify_sign_show_text = 1
let g:signify_sign_add = '▊'
let g:signify_sign_change = '▊'
let g:signify_sign_delete = '▊'
```

**Comment by jamessan** [comment]
Maybe `let g:signify_sign_add = "\ua0"` to be a little more friendly.

**Comment by mhinz** [comment]
@jose4125 `g:signify_sign_show_text` got removed now.

If you want that old behaviour of just having a block of one color as a sign, just use this:

```vim
let g:signify_sign_add = '██'
let g:signify_sign_change = '██'
let g:signify_sign_delete = '██'
```

You also don't need the extra highlight groups anymore. And if you want to change the colors, use this:

```vim
highlight SignifySignAdd    ctermfg=green  guifg=#00ff00 cterm=NONE gui=NONE
highlight SignifySignDelete ctermfg=red    guifg=#ff0000 cterm=NONE gui=NONE
highlight SignifySignChange ctermfg=yellow guifg=#ffff00 cterm=NONE gui=NONE
```
