### ISSUE TITLE
Show differences when starting vim from another directory

### ISSUE THREAD

**Issue by oren0e** [mhinz/vim-signify#376]
Let's say I'm in folder `/src/folders` and in `folders` I have several subdirectories with different projects: `proj_a`, `proj_b`, and `proj_c`. If I start vim from `/src/folders` and then navigate (with nerdTree for example) to work on `proj_a`, then vim-signify does not show me anything when I change files. Can this be altered? I don't want to actually `cd` to each project every time.

**Comment by jamessan** [comment]
Please reopen if you have more information, for example the output of `:SignifyDebug` in a buffer that isn't behaving as you expect.
