### ISSUE TITLE
Can't achieve realtime feedback

### ISSUE THREAD

**Issue by carljohnesan** [mhinz/vim-signify#379]
Hello there. So I have following configuration for signify in my `.vimrc`:
```vim
let g:signify_realtime=1

nmap <Leader>hd :SignifyHunkDiff<cr>
```

Output of `:au signify`:
```
--- Autocommands ---
signify  BufEnter
    <buffer=1>
              call sy#start()
signify  BufWritePost
    <buffer=1>
              call sy#start()
signify  CmdWinEnter
    <buffer=1>
              let g:signify_cmdwin_active = 1
signify  CmdWinLeave
    <buffer=1>
              let g:signify_cmdwin_active = 0
signify  CursorHold
    <buffer=1>
              call sy#start()
signify  CursorHoldI
    <buffer=1>
              call sy#start()
signify  FocusGained
    <buffer=1>
              SignifyRefresh
signify  ShellCmdPost
    <buffer=1>
              call sy#start()
signify  VimResume
    <buffer=1>
              call sy#start()
signify  WinEnter
    <buffer=1>
              call sy#start()
```

I don't know why but as I make changes to the code either in insert or in normal mode, diff signs don't get updated until I`:write` the file. Please help me solve this problem.

**Comment by jamessan** [comment]
`CursorHold` and `CursorHoldI` get triggered based on the interval specified in the [`'updatetime'`](https://vimhelp.org/options.txt.html#%27updatetime%27).  Either you have that set to a large value or you're not waiting that duration of time for Signify to update.
