### ISSUE TITLE
Show git changes by colour

### ISSUE THREAD

**Issue by dob9601** [mhinz/vim-signify#383]
Using the `signcolumn=number` setting can often lead to a git changes in the columns obscuring line numbers:
![image](https://user-images.githubusercontent.com/24723950/133167688-43e30c8b-ac3e-4db4-b681-82c6a62baadc.png)
Would it be possible to show the colours without the text? Potentially by having a sign with the value of the line number its on

**Comment by jamessan** [comment]
https://github.com/mhinz/vim-signify/issues/374#issuecomment-829356399

https://github.com/mhinz/vim-signify/blob/22f05607d4d7406781af56cafc1121152988c6d2/doc/signify.txt#L281-L288
