### ISSUE TITLE
Is it possible to color the line number instead of a sign?

### ISSUE THREAD

**Issue by epigramengineer** [mhinz/vim-signify#387]
So I've figured out how to display the sign in the number column which I find more compact, but when I have a large addition that means I lose all context of what lines I am on. Is there a way to get a highlight group like `SignifyLineAdd` that is effectively `SignifyLineNrAdd` so that I can just color my line numbers instead of showing a symbol at all? (I've read through the help on signify-colors, looked through other issues, and googled around for a good bit but can't seem to find anything)

**Comment by jamessan** [comment]
Neovim has support for a `numhl` attribute in a sign, so if you're using that we could add support for it to Neovim.  Otherwise, you'd need to get that functionality merged into Vim.

**Comment by jamessan** [comment]
@epigramengineer With #388, you can set all the sign text to empty strings and `g:signify_number_highlight=1`, which should do what you want.
