### ISSUE TITLE
Custom `numhl` highlightings are ignored

### ISSUE THREAD

**Issue by Edenhofer** [mhinz/vim-signify#390]
Previously highlighting line numbers was possible without any additional options in vim-signify using a configuration similar to the one below. In e0982523d5558b67eac1e6e6acf775efc021fbc0 number highlighting were added and now the below definitions take no effect regardless of whether `g:signify_number_highlight` is set or not.

```vimrc
" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-signify'  " VCS sign indicators
call plug#end()

set number
set signcolumn=no  " Disable the sign column and instead color the line numbers

let g:signify_sign_show_count=0
" let g:signify_number_highlight=1

highlight VCSRemove guibg=#51202A guifg=#FF0000 gui=bold

sign define SignifyAdd text=+ linehl= texthl= numhl=VCSRemove
sign define SignifyChange text=! linehl= texthl= numhl=VCSRemove
sign define SignifyChangeDelete text=!‾ linehl= texthl= numhl=VCSRemove
sign define SignifyRemoveFirstLine text=‾ linehl= texthl= numhl=VCSRemove
sign define SignifyDeleteMore text=_ linehl= texthl= numhl=VCSRemove
```

In which way do I need to adapt my configuration so that my custom highlightings take effect again?

Furthermore, would it be possible to keep track of such breaking changes in a dedicated bug ticket to which one could subscribe to (similar to e.g. https://github.com/hrsh7th/nvim-cmp/issues/231)?

**Comment by jamessan** [comment]
> ```viml
> sign define SignifyAdd text=+ linehl= texthl= numhl=VCSRemove
> sign define SignifyChange text=! linehl= texthl= numhl=VCSRemove
> sign define SignifyChangeDelete text=!‾ linehl= texthl= numhl=VCSRemove
> sign define SignifyRemoveFirstLine text=‾ linehl= texthl= numhl=VCSRemove
> sign define SignifyDeleteMore text=_ linehl= texthl= numhl=VCSRemove
> ```

This is the wrong way to customize the highlighting.  You were just lucky that we weren't using `numhl` before.  If you run `:sign list`, you'll see that the signs have been re-defined and have `texthl` set.

The proper way to customize the highlighting is to customize the Signify highlight groups, as described in `:help signify-colors`.

> Furthermore, would it be possible to keep track of such breaking changes

This wasn't a breaking change.

**Comment by Edenhofer** [comment]
Thank you for your comment! I had a wrong concept in mind of when signs are defined. It really was luck rather than a feature of Signify that it worked before. I'll use `sign define Signify*` form now on then.
