### ISSUE TITLE
Vim-signify does not work.

### ISSUE THREAD

**Issue by fernandofriasfernandez** [mhinz/vim-signify#391]
I have recently discovered **vim-signify**. I like it, but the problem is that I cannot use it because it does not work. 
I use vim-plug, so I installed the plugin with `Plug 'mhinz/vim-signify'` and then I did `:PlugInstall`. 
After that, I tested it by adding, modifying and deleting lines of a file but it did not show the signs.
I use Linux Mint, and my neovim version is **NVIM v0.5.0**.

**Comment by jamessan** [comment]
What does `:SignifyDebug` show in the buffer where it's not working?

**Comment by fernandofriasfernandez** [comment]
I tried adding, modifying lines and deleting on various files, but it does not work on any of them. 
When I did `:SignifyDebug` it showed this: **signify: I cannot detect any changes!**.

**Comment by jamessan** [comment]
Is the file you're editing under version control?  If not, then this is behaving as intended.  Signify can only show changes to a version controlled file.

**Comment by fernandofriasfernandez** [comment]
What is version controlled file? How can my files be under version control?

**Comment by jamessan** [comment]
By using a version control tool, like git, svn, mercurial, etc.  This is all described in the README.
