### ISSUE TITLE
Support environment variables in diff commands

### ISSUE THREAD

**Issue by ppwwyyxx** [mhinz/vim-signify#405]
My company has a fairly complex (and useful) hg configuration which, for reasons I don't fully understand, does not work with the default hg command in this repo (which is `hg diff --color=never --config aliases.diff= --nodates -U0 -- %f`) due to various aliases and pager settings.

What works in our mercurial repo is to add a `HGPLAIN=1` environment variable.

According to mercurial docs: https://www.mercurial-scm.org/repo/hg/help/environment , `HGPLAIN` disables all configurations. So it should generally work better than `--config aliases.diff=`.

However, I cannot set the command to 
```
let g:signify_vcs_cmds = {'hg': 'HGPLAIN=1 hg diff --color=never  --nodates -U0 -- %f' }
```
because signify will try to check that the executable "HGPLAIN=1" exists (which it does not) and assume hg is not available on the machine.

My current workaround is:
```
let g:signify_vcs_cmds = {'hg': 'env HGPLAIN=1 hg diff --color=never --nodates -U0 -- %f' }
```

I hope signify can improve its logic of checking executables, such that environment variables can be easily supported.

**Comment by jamessan** [comment]
> My current workaround is:
> 
> ```
> let g:signify_vcs_cmds = {'hg': 'env HGPLAIN=1 hg diff --color=never --nodates -U0 -- %f' }
> ```

That's the portable way to do it, not a workaround.

You could probably also put `let $HGPLAIN=1` in your vimrc instead.
