### ISSUE TITLE
`Key not present in Dictionary` errors when using `g:signify_vcs_cmds`

### ISSUE THREAD

**Issue by jeroen-dhollander** [mhinz/vim-signify#410]
I use signify only for `git` but I want to diff against upstream so I am using the following setup:

```
let g:signify_vcs_list = ['git']
" Diff against upstream
let g:signify_vcs_cmds = {
    \ 'git': 'git diff @{upstream} --no-color --no-ext-diff -U0 -- %f'
 \ }
```

However when loading any file (in a git repository) I get an error complaining that the `rcs` key is missing from this dictionary:

![signify_error](https://github.com/mhinz/vim-signify/assets/10767030/b0f47c88-d390-423a-b7ba-49c5432c4736)

If I add an entry for `rcs` to `g:signify_vcs_cmds` it starts complaining about `svn` missing (and so on).

This means I can work around this by adding empty entries for all other version control systems, but that doesn't look ideal to me :upside_down_face: 

```
`let g:signify_vcs_cmds = {
    \ 'git': 'git diff @{upstream} --no-color --no-ext-diff -U0 -- %f',
    \ 'rcs': 'Adding something to work around bug',
    \ 'svn': '',
    \ 'hg': '',
    \ 'darcs': '',
    \ 'bzr': '',
    \ 'cvs': '',
    \ 'fossil': '',
    \ 'accurev': '',
    \ 'perforce': '',
    \ 'tfs': '',
    \ 'yadm': ''
 \ }
```

For reference I updated Signify today (my checkout is at today's  latest commit [7d538b7](https://github.com/mhinz/vim-signify/commit/7d538b77a5a8806e344b057f8846f6d0c035efa9)).

**Comment by jamessan** [comment]
`g:signify_vcs_list` isn't used anymore.  You probably want to use `g:signify_skip`.

Also, defining a `g:signify_vcs_cmds` is just a way to override the command used for a specific VCS, not to exclude ones that are used.  We just merge the default values into the user-provided `g:signify_vcs_cmds`.

That being said, I can't currently reproduce the issue you're seeing.  Hopefully using `g:signify_skip` addresses it.

**Comment by jeroen-dhollander** [comment]
Thanks for the reply. The issue seems to be fixed by using `g:signify_skip`, so thanks!

> Also, defining a g:signify_vcs_cmds is just a way to override the command used for a specific VCS, not to exclude ones that are used.

I know, and that's why I am using it (I want git to diff against the upstream not just against HEAD).
