### ISSUE TITLE
fossil: -c 0 currently (<=fossil-2.23) does not work as expected (uses default number of context lines)

### ISSUE THREAD

**Issue by berndf** [mhinz/vim-signify#412]
Just for the record: For fossil, 'fossil diff --unified -c 0 -- %f' is used but '-c 0' is currently just ignored by fossil, so the change marks shown by signify span 5 more lines than intended on either side of the actual change.

This is just to note the discussion at https://fossil-scm.org/forum/forumpost/b5e4e80a63 which lets me hope that '-c 0' will be supported in the future.

**Comment by jamessan** [comment]
Looks like it was fixed the same day. :) Thanks for discussing with upstream and letting folks know here. Since there's nothing left to do in Sy, I'm going to close this.
